
const playerInjuries = {
    lastUpdatedOn: data.lastUpdatedOn,
    playerId: data.players[0].id,
    playerFirstName: data.players[0].firstName,
    playerLastName: data.players[0].lastName,
    playerPrimaryPosition: data.players[0].primaryPosition,
    playerJerseyNumber: data.players[0].jerseyNumber,
    currentTeamId: data.players[0].currentTeam.id,
    currentTeamAbbreviation: data.players[0].currentTeam.abbreviation,
    currentRosterStatus: data.players[0].currentRosterStatus,
    currentInjuries: data.players[0].currentInjuries,
    currentInjuryDescription: data.players[0].currentInjury.description,
    currentInjuryPlayingProbability: data.players[0].currentInjury.playingProbability,
    playerHeight: data.players[0].height,
    playerWeight: data.players[0].weight,
    playerBirthDate: data.players[0].birthDate,
    playerAge: data.players[0].age,
    playerBirthCity: data.players[0].birthCity,
    playerHighSchool: data.players[0].highSchool,
    playerCollege: data.players[0].college,
    handednessShoots: data.players[0].shoots,
    playerOfficialImageSrc: data.players[0].officialImageSrc,
    playerSocialMediaAccountsMediaType: data.players[0].mediaTypes,
    playerSocialMediaAccountsValue: data.players[0].values
};


const dailyPlayerGameLogs = {
    latestUpdatedOn: data.lastUpdatedOn,
    gameId: data.gamelogs[0].game.id,
    gameStartTime: data.gamelogs[0].game.startTime,
    gamesAwayTeamAbbreviation: data.gamelogs[0].game.awayTeamAbbreviation,
    gamesHomeTeamAbbreviation: data.gamelogs[0].game.homeTeamAbbreviation,
    playerId: data.gamelogs[0].player.id,
    playerFirstName: data.gamelogs[0].player.firstName,
    playerLastName: data.gamelogs[0].player.lastName,
    playerPosition: data.gamelogs[0].player.position,
    playerJerseyNumber: data.gamelogs[0].player.jerseyNumber,
    teamId: data.gamelogs[0].team.id,
    teamAbbreviation: data.gamelogs[0].team.abbreviation,
    statsFieldGoalsFg2PtAtt: data.gamelogs[0].stats.fieldGoals.fg2PtAtt,
    statsFieldGoalsFg2PtAttPerGame: data.gamelogs[0].stats.fieldGoals.fg2PtAttPerGame,
    statsFieldGoalsFg2PtMade: data.gamelogs[0].stats.fieldGoals.fg2PtMade,   
    statsFieldGoalsFg2PtMadePerGame: data.gamelogs[0].stats.fieldGoals.fg2PtMadePerGame,
    statsFieldGoalsFg2PtPct: data.gamelogs[0].stats.fieldGoals.fg2PtPct,
    statsFieldGoalsFg3PtAtt: data.gamelogs[0].stats.fieldGoals.fg3PtAtt,
    statsFieldGoalsFg3PtAttPerGame: data.gamelogs[0].stats.fieldGoals.fg3PtAttPerGame,
    statsFieldGoalsFg3PtMade: data.gamelogs[0].stats.fieldGoals.fg3PtMade,
    statsFieldGoalsFg3PtMadePerGame: data.gamelogs[0].stats.fieldGoals.fg3PtMadePerGame,
    statsFieldGoalsFg3PtPct: data.gamelogs[0].stats.fieldGoals.fg3PtPct,
    statsFieldGoalsfgAtt: data.gamelogs[0].stats.fieldGoals.fgAtt,
    statsFieldGoalsfgAttPerGame: data.gamelogs[0].stats.fieldGoals.fgAttPerGame,
    statsFieldGoalsfgMade: data.gamelogs[0].stats.fieldGoals.fgMade,
    statsFieldGoalsfgMadePerGame: data.gamelogs[0].stats.fieldGoals.fgMadePerGame,
    statsFieldGoalsfgPct: data.gamelogs[0].stats.fieldGoals.fgPct,
    statsFreeThrowsFtAtt: data.gamelogs[0].stats.freeThrows.ftAtt,
    statsFreeThrowsFtAttPerGame: data.gamelogs[0].stats.freeThrows.ftAttPerGame,
    statsFreeThrowsFtMade: data.gamelogs[0].stats.freeThrows.ftMade,
    statsFreeThrowsFtMadePerGame: data.gamelogs[0].stats.freeThrows.ftMadePerGame,
    statsFreeThrowsFtPct: data.gamelogs[0].stats.freeThrows.ftPct,
    statsReboundsOffReb: data.gamelogs[0].stats.rebounds.offReb,
    statsReboundsOffRebPerGame: data.gamelogs[0].stats.rebounds.offRebPerGame,
    statsReboundsDefReb: data.gamelogs[0].stats.rebounds.defReb,
    statsReboundsDefRebPerGame: data.gamelogs[0].stats.rebounds.defRebPerGame,
    statsReboundsReb: data.gamelogs[0].stats.rebounds.reb,
    statsReboundsRebPerGame: data.gamelogs[0].stats.rebounds.rebPerGame,
    statsOffenseAst: data.gamelogs[0].stats.offense.ast,
    statsOffenseAstPerGame: data.gamelogs[0].stats.offense.astPerGame,
    statsOffensePts: data.gamelogs[0].stats.offense.pts,
    statsOffensePtsPerGame: data.gamelogs[0].stats.offense.ptsPerGame,
    statsDefenseTov: data.gamelogs[0].stats.defense.tov,
    statsDefenseTovPerGame: data.gamelogs[0].stats.defense.tovPerGame,
    statsDefenseStl: data.gamelogs[0].stats.defense.stl,
    statsDefenseStlPerGame: data.gamelogs[0].stats.defense.stlPerGame,
    statsDefenseBlk: data.gamelogs[0].stats.defense.blk,
    statsDefenseBlkPerGame: data.gamelogs[0].stats.defense.blkPerGame,
    statsDefenseBlkAgainst: data.gamelogs[0].stats.defense.blkAgainst,
    statsDefenseBlkAgainstPerGame: data.gamelogs[0].stats.defense.blkAgainstPerGame,
    
    statsMiscellaneousFouls: data.gamelogs[0].stats.miscellaneous.fouls,
    statsMiscellaneousFoulsPerGame: data.gamelogs[0].stats.miscellaneous.foulsPerGame,
    statsMiscellaneousFoulsDrawn: data.gamelogs[0].stats.miscellaneous.foulsDrawn,
    statsMiscellaneousFoulsDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulsDrawnPerGame,
    statsMiscellaneousFoulPers: data.gamelogs[0].stats.miscellaneous.foulPers,
    statsMiscellaneousFoulPersPerGame: data.gamelogs[0].stats.miscellaneous.foulPersPerGame,
    statsMiscellaneousFoulPersDrawn: data.gamelogs[0].stats.miscellaneous.foulPersDrawn,
    statsMiscellaneousFoulPersDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulPersDrawnPerGame,
   
    statsMiscellaneousFoulTech: data.gamelogs[0].stats.miscellaneous.foulTech,
    statsMiscellaneousFoulTechPerGame: data.gamelogs[0].stats.miscellaneous.foulTechPerGame,
    statsMiscellaneousFoulTechDrawn: data.gamelogs[0].stats.miscellaneous.foulTechDrawn,
    statsMiscellaneousFoulTechDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulTechDrawnPerGame,
    statsMiscellaneousFoulFlag1: data.gamelogs[0].stats.miscellaneous.foulFlag1,
    statsMiscellaneousFoulFlag1PerGame: data.gamelogs[0].stats.miscellaneous.foulFlag1PerGame,
    statsMiscellaneousFoulFlag1Drawn: data.gamelogs[0].stats.miscellaneous.foulFlag1Drawn,
    statsMiscellaneousFoulFlag1DrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulFlag1DrawnPerGame,
    statsMiscellaneousFoulFlag2: data.gamelogs[0].stats.miscellaneous.foulFlag2,
    statsMiscellaneousFoulFlag2PerGame: data.gamelogs[0].stats.miscellaneous.foulFlag2PerGame,
    statsMiscellaneousFoulFlage2Drawn: data.gamelogs[0].stats.miscellaneous.foulFlag2Drawn,
    statsMiscellaneousFoulFlag2DrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulFlag2DrawnPerGame,

    statsMiscellaneousEjections: data.gamelogs[0].stats.miscellaneous.ejections,
    statsMiscellaneousPlusMinus: data.gamelogs[0].stats.miscellaneous.plusMinus,
    statsMiscellaneousPlusMInusPerGame: data.gamelogs[0].stats.miscellaneous.plusMinusPerGame,
    statsMiscellaneousMinSeconds: data.gamelogs[0].stats.miscellaneous.minSeconds,
    statsMiscellaneousMinSecondsPerGame: data.gamelogs[0].stats.miscellaneous.minSecondsPerGame,
    statsMiscellaneousGameStarted: data.gamelogs[0].stats.miscellaneous.gamesStarted
}

