players.[key].d

const API = {
    players: (data) => {
        const players = {
            plyrLastUpdatedOn: [data.lastUpdatedOn, "Last Updated On"],
            plyrId: data.players[0].player.id,
            plyrFirstName: data.players[0].player.firstName,
            plyrLastName: data.players[0].player.lastName,
            plyrPrimaryPosition: data.players[0].player.primaryPosition,
            plyrAlternatePositions: data.players[0].player.alternatePositions,
            plyrJerseyNumber: data.players[0].player.jerseyNumber,
            plyrCurrentTeamId: data.players[0].player.currentTeam.id,
            plyrCurrentTeamAbbreviation: data.players[0].player.currentTeam.abbreviation,
            plyrCurrentRosterStatus: data.players[0].player.currentRosterStatus,
            plyrCurrentInjury: data.players[0].player.currentInjury,
            plyrHeight: data.players[0].player.height,
            plyrWeight: data.players[0].player.weight,
            plyrBirthDate: data.players[0].player.birthDate,
            plyrAge: data.players[0].player.age,
            plyrBirthCity: data.players[0].player.birthCity,
            plyrBirthCountry: data.players[0].player.birthCountry,
            plyrRookie: data.players[0].player.rookie,
            plyrHighSchool: data.players[0].player.highSchool,
            plyrCollege: data.players[0].player.college,
            plyrHandednessShoots: data.players[0].player.handedness.shoots,
            plyrOfficialImageSrc: data.players[0].player.officialImageSrc,
            plyrSocialMediaAccounts: data.players[0].player.socialMediaAccounts,
            plyrCurrentContractYear: data.players[0].player.currentContractYear,
            plyrDraftedYear: data.players[0].player.drafted.year,
            plyrDraftedTeamId: data.players[0].player.drafted.team.id,
            plyrDraftedTeamAbbreviation: data.players[0].player.drafted.team.abbreviation,
            plyrDraftedPickTeamId: data.players[0].player.drafted.pickTeam.id,
            plyrDraftedPickTeamAbbreviation: data.players[0].player.drafted.pickTeam.abbreviation,
            plyrDraftedRound: data.players[0].player.drafted.round,
            plyrDraftedRoundPick: data.players[0].player.drafted.roundPick,
            plyrOverallPick: data.players[0].player.drafted.overallPick,
            plyrExternalMappingsSource: data.players[0].player.externalMappings[0].source,
            plyrExternalMappingsId: data.players[0].player.externalMappings[0].id,
            plyrTeamAsOfDateId: data.players[0].teamAsOfDate.id,
            plyrTeamAsOfDateAbbreviation: data.players[0].teamAsOfDate.abbreviation
        }
        return players;
    },
    playerInjuries: (data) => {
        const playerInjuries = {
            plijLastUpdatedOn: data.lastUpdatedOn,
            plijId: data.players[0].id,
            plijFirstName: data.players[0].firstName,
            plijLastName: data.players[0].lastName,
            plijPrimaryPosition: data.players[0].primaryPosition,
            plijJerseyNumber: data.players[0].jerseyNumber,
            plijCurrentTeamId: data.players[0].currentTeam.id,
            plijCurrentTeamAbbreviation: data.players[0].currentTeam.abbreviation,
            plijCurrentRosterStatus: data.players[0].currentRosterStatus,
            plijCurrentInjuries: data.players[0].currentInjuries,
            plijCurrentInjuryDescription: data.players[0].currentInjury.description,
            plijCurrentInjuryPlayingProbability: data.players[0].currentInjury.playingProbability,
            plijHeight: data.players[0].height,
            plijWeight: data.players[0].weight,
            plijBirthDate: data.players[0].birthDate,
            plijAge: data.players[0].age,
            plijBirthCity: data.players[0].birthCity,
            plijHighSchool: data.players[0].highSchool,
            plijCollege: data.players[0].college,
            plijHandednessShoots: data.players[0].shoots,
            plijOfficialImageSrc: data.players[0].officialImageSrc,
            plijSocialMediaAccountsMediaType: data.players[0].mediaTypes,
            plijSocialMediaAccountsValue: data.players[0].value
        }
        return playerInjuries;
    },
    dailyPlayerGameLogs: (data) => {
        const dailyPlayerGameLogs = {
            dpglLatestUpdatedOn: data.lastUpdatedOn,
            dpglGameId: data.gamelogs[0].game.id,
            dpglGameStartTime: data.gamelogs[0].game.startTime,
            dpglGamesAwayTeamAbbreviation: data.gamelogs[0].game.awayTeamAbbreviation,
            dpglGamesHomeTeamAbbreviation: data.gamelogs[0].game.homeTeamAbbreviation,
            dpglPlayerId: data.gamelogs[0].player.id,
            dpglPlayerFirstName: data.gamelogs[0].player.firstName,
            dpglPlayerLastName: data.gamelogs[0].player.lastName,
            dpglPlayerPosition: data.gamelogs[0].player.position,
            dpglPlayerJerseyNumber: data.gamelogs[0].player.jerseyNumber,
            dpglTeamId: data.gamelogs[0].team.id,
            dpglTeamAbbreviation: data.gamelogs[0].team.abbreviation,
            dpglFg2PtAtt: data.gamelogs[0].stats.fieldGoals.fg2PtAtt,
            dpglFg2PtAttPerGame: data.gamelogs[0].stats.fieldGoals.fg2PtAttPerGame,
            dpglFg2PtMade: data.gamelogs[0].stats.fieldGoals.fg2PtMade,  
            dpglFg2PtMadePerGame: data.gamelogs[0].stats.fieldGoals.fg2PtMadePerGame,
            dpglFg2PtPct: data.gamelogs[0].stats.fieldGoals.fg2PtPct,
            dpglFg3PtAtt: data.gamelogs[0].stats.fieldGoals.fg3PtAtt,
            dpglFg3PtAttPerGame: data.gamelogs[0].stats.fieldGoals.fg3PtAttPerGame,
            dpglFg3PtMade: data.gamelogs[0].stats.fieldGoals.fg3PtMade,
            dpglFg3PtMadePerGame: data.gamelogs[0].stats.fieldGoals.fg3PtMadePerGame,
            dpglFg3PtPct: data.gamelogs[0].stats.fieldGoals.fg3PtPct,
            dpglFgAtt: data.gamelogs[0].stats.fieldGoals.fgAtt,
            dpglFgAttPerGame: data.gamelogs[0].stats.fieldGoals.fgAttPerGame,
            dpglFgMade: data.gamelogs[0].stats.fieldGoals.fgMade,
            dpglFgMadePerGame: data.gamelogs[0].stats.fieldGoals.fgMadePerGame,
            dpglFgPct: data.gamelogs[0].stats.fieldGoals.fgPct,
            dpglFtAtt: data.gamelogs[0].stats.freeThrows.ftAtt,
            dpglFtAttPerGame: data.gamelogs[0].stats.freeThrows.ftAttPerGame,
            dpglFtMade: data.gamelogs[0].stats.freeThrows.ftMade,
            dpglFtMadePerGame: data.gamelogs[0].stats.freeThrows.ftMadePerGame,
            dpglFtPct: data.gamelogs[0].stats.freeThrows.ftPct,
            dpglOffReb: data.gamelogs[0].stats.rebounds.offReb,
            dpglOffRebPerGame: data.gamelogs[0].stats.rebounds.offRebPerGame,
            dpglDefReb: data.gamelogs[0].stats.rebounds.defReb,
            dpglDefRebPerGame: data.gamelogs[0].stats.rebounds.defRebPerGame,
            dpglReb: data.gamelogs[0].stats.rebounds.reb,
            dpglRebPerGame: data.gamelogs[0].stats.rebounds.rebPerGame,
            dpglAst: data.gamelogs[0].stats.offense.ast,
            dpglAstPerGame: data.gamelogs[0].stats.offense.astPerGame,
            dpglPts: data.gamelogs[0].stats.offense.pts,
            dpglPtsPerGame: data.gamelogs[0].stats.offense.ptsPerGame,
            dpglTov: data.gamelogs[0].stats.defense.tov,
            dpglTovPerGame: data.gamelogs[0].stats.defense.tovPerGame,
            dpglStl: data.gamelogs[0].stats.defense.stl,
            dpglStlPerGame: data.gamelogs[0].stats.defense.stlPerGame,
            dpglBlk: data.gamelogs[0].stats.defense.blk,
            dpglBlkPerGame: data.gamelogs[0].stats.defense.blkPerGame,
            dpglBlkAgainst: data.gamelogs[0].stats.defense.blkAgainst,
            dpglBlkAgainstPerGame: data.gamelogs[0].stats.defense.blkAgainstPerGame,
            // miscelleneous: dailyPlayerGameLogs
            dpglFouls: data.gamelogs[0].stats.miscellaneous.fouls,
            dpglFoulsPerGame: data.gamelogs[0].stats.miscellaneous.foulsPerGame,
            dpglFoulsDrawn: data.gamelogs[0].stats.miscellaneous.foulsDrawn,
            dpglFoulsDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulsDrawnPerGame,
            dpglFoulPers: data.gamelogs[0].stats.miscellaneous.foulPers,
            dpglFoulPersPerGame: data.gamelogs[0].stats.miscellaneous.foulPersPerGame,
            dpglFoulPersDrawn: data.gamelogs[0].stats.miscellaneous.foulPersDrawn,
            dpglFoulPersDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulPersDrawnPerGame,
    
            dpglFoulTech: data.gamelogs[0].stats.miscellaneous.foulTech,
            dpglFoulTechPerGame: data.gamelogs[0].stats.miscellaneous.foulTechPerGame,
            dpglFoulTechDrawn: data.gamelogs[0].stats.miscellaneous.foulTechDrawn,
            dpglFoulTechDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulTechDrawnPerGame,
            dpglFoulFlag1: data.gamelogs[0].stats.miscellaneous.foulFlag1,
            dpglFoulFlag1PerGame: data.gamelogs[0].stats.miscellaneous.foulFlag1PerGame,
            dpglFoulFlag1Drawn: data.gamelogs[0].stats.miscellaneous.foulFlag1Drawn,
            dpglFoulFlag1DrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulFlag1DrawnPerGame,
            dpglFoulFlag2: data.gamelogs[0].stats.miscellaneous.foulFlag2,
            dpglFoulFlag2PerGame: data.gamelogs[0].stats.miscellaneous.foulFlag2PerGame,
            dpglFoulFlage2Drawn: data.gamelogs[0].stats.miscellaneous.foulFlag2Drawn,
            dpglFoulFlag2DrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulFlag2DrawnPerGame,
        
            dpglEjections: data.gamelogs[0].stats.miscellaneous.ejections,
            dpglPlusMinus: data.gamelogs[0].stats.miscellaneous.plusMinus,
            dpglPlusMInusPerGame: data.gamelogs[0].stats.miscellaneous.plusMinusPerGame,
            dpglMinSeconds: data.gamelogs[0].stats.miscellaneous.minSeconds,
            dpglMinSecondsPerGame: data.gamelogs[0].stats.miscellaneous.minSecondsPerGame,
            dpglGamesStarted: data.gamelogs[0].stats.miscellaneous.gamesStarted
        }
        return dailyPlayerGameLogs;
    },
    dailyTeamGamelogs: (data) => {
        const dailyTeamGamelogs = {
            dtglLastUpdatedOn: data.lastUpdatedOn,
            dtglGameId: data.gamelogs[0].game.id,
            dtglGameStartTime: data.gamelogs[0].game.startTime,
            dtglGameAwayTeamAbbreviation: data.gamelogs[0].game.awayTeamAbbreviation,
            dtglGameHomeTeamAbbreviation: data.gamelogs[0].game.homeTeamAbbreviation,
            dtglTeamId: data.gamelogs[0].team.id,
            dtglTeamAbbreviation: data.gamelogs[0].team.abbreviation,
            // 2pt field goals: dailyTeamGameLogs
            dtglFg2PtAtt: data.gamelogs[0].stats.fieldGoals.fg2PtAtt,
            dtglFg2PtAttPerGame: data.gamelogs[0].stats.fieldGoals.fg2PtAttPerGame,
            dtglFg2PtMade: data.gamelogs[0].stats.fieldGoals.fg2PtMade,
            dtglFg2PtMadePerGame: data.gamelogs[0].stats.fieldGoals.fg2PtMadePerGame,
            dtglFg2PtPct: data.gamelogs[0].stats.fieldGoals.fg2PtPct,
            // 3pt field goals: dailyTeamGameLogs
            dtglFg3PtAtt: data.gamelogs[0].stats.fieldGoals.fg3PtAtt,
            dtglFg3PtAttPerGame: data.gamelogs[0].stats.fieldGoals.fg3PtAttPerGame,
            dtglFg3PtMade: data.gamelogs[0].stats.fieldGoals.fg3PtMade,
            dtglFg3PtMadePerGame: data.gamelogs[0].stats.fieldGoals.fg3PtMadePerGame,
            dtglFg3PtPct: data.gamelogs[0].stats.fieldGoals.fg3PtPct,
            // total field goals: dailyTeamGameLogs
            dtglFgAtt: data.gamelogs[0].stats.fieldGoals.fgAtt,
            dtglFgAttPerGame: data.gamelogs[0].stats.fieldGoals.fgAttPerGame,
            dtglFgMade: data.gamelogs[0].stats.fieldGoals.fgMade,
            dtglFgMadePerGame: data.gamelogs[0].stats.fieldGoals.fgMadePerGame,
            dtglFgPct: data.gamelogs[0].stats.fieldGoals.fgPct,
            // free throws: dailyTeamGameLogs
            dtglFtAtt: data.gamelogs[0].stats.freeThrows.ftAtt,
            dtglFtAttPerGame: data.gamelogs[0].stats.freeThrows.ftAttPerGame,
            dtglFtMade: data.gamelogs[0].stats.freeThrows.ftMade,
            dtglFtMadePerGame: data.gamelogs[0].stats.freeThrows.ftMadePerGame,
            dtglFtPct: data.gamelogs[0].stats.freeThrows.ftPct,
            // rebounds: dailyTeamGameLogs
            dtglOffReb: data.gamelogs[0].stats.rebounds.offReb,
            dtglOffRebPerGame: data.gamelogs[0].stats.rebounds.offRebPerGame,
            dtglDefReb: data.gamelogs[0].stats.rebounds.defReb,
            dtglDefRebPerGame: data.gamelogs[0].stats.rebounds.defRebPerGame,
            dtglReb: data.gamelogs[0].stats.rebounds.reb,
            dtglRebPerGame: data.gamelogs[0].stats.rebounds.rebPerGame,
            // offense: dailyTeamGameLogs
            dtglAst: data.gamelogs[0].stats.offense.ast,
            dtglAstPerGame: data.gamelogs[0].stats.offense.astPerGame,
            dtglPts: data.gamelogs[0].stats.offense.pts,
            dtglPtsPerGame: data.gamelogs[0].stats.offense.ptsPerGame,
            // defense: dailyTeamGameLogs
            dtglTov: data.gamelogs[0].stats.defense.tov,
            dtglTovPerGame: data.gamelogs[0].stats.defense.tovPerGame,
            dtglStl: data.gamelogs[0].stats.defense.stl,
            dtglStlPerGame: data.gamelogs[0].stats.defense.stlPerGame,
            dtglBlk: data.gamelogs[0].stats.defense.blk,
            dtglBlkPerGame: data.gamelogs[0].stats.defense.blkPerGame,
            dtglBlkAgainst: data.gamelogs[0].stats.defense.blkAgainst,
            dtglBlkAgainstPerGame: data.gamelogs[0].stats.defense.blkAgainstPerGame,
            dtglPtsAgainst: data.gamelogs[0].stats.defense.ptsAgainst,
            dtglPtsAgainstPerGame: data.gamelogs[0].stats.defense.ptsAgainstPerGame,
            // miscellaneous: dailyTeamGameLogs
            dtglFouls: data.gamelogs[0].stats.miscellaneous.fouls,
            dtglFoulsPerGame: data.gamelogs[0].stats.miscellaneous.foulsPerGame,
            dtglFoulsDrawn: data.gamelogs[0].stats.miscellaneous.foulsDrawn,
            dtglFoulsDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulsDrawnPerGame,
            dtglFoulPers: data.gamelogs[0].stats.miscellaneous.foulPers,
            dtglFoulPersPerGame: data.gamelogs[0].stats.miscellaneous.foulPersPerGame,
            dtglFoulPersDrawn: data.gamelogs[0].stats.miscellaneous.foulPersDrawn,
            dtglFoulPersDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulPersDrawnPerGame,
            dtglFoulTech: data.gamelogs[0].stats.miscellaneous.foulTech,
            dtglFoulTechPerGame: data.gamelogs[0].stats.miscellaneous.foulTechPerGame,
            dtglFoulTechDrawn: data.gamelogs[0].stats.miscellaneous.foulTechDrawn,
            dtglFoulTechDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulTechDrawnPerGame,
            dtglFoulFlag1: data.gamelogs[0].stats.miscellaneous.foulFlag1,
            dtglFoulFlag1PerGame: data.gamelogs[0].stats.miscellaneous.foulFlag1PerGame,
            dtglFoulFlag1Drawn: data.gamelogs[0].stats.miscellaneous.foulFlag1Drawn,
            dtglFoulFlag1DrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulFlag1DrawnPerGame,
            dtglFoulFlag2: data.gamelogs[0].stats.miscellaneous.foulFlag2,
            dtglFoulFlag2PerGame: data.gamelogs[0].stats.miscellaneous.foulFlag2PerGame,
            dtglFoulFlag2Drawn: data.gamelogs[0].stats.miscellaneous.foulFlag2Drawn,
            dtglFoulFlag2DrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulFlag2DrawnPerGame,
            dtglEjections: data.gamelogs[0].stats.miscellaneous.ejections,
            dtglPlusMinus: data.gamelogs[0].stats.miscellaneous.plusMinus,
            dtglPlusMinusPerGame: data.gamelogs[0].stats.miscellaneous.plusMinusPerGame,
            // standings: dailyTeamGameLogs
            dtglWins: data.gamelogs[0].stats.standings.wins,
            dtglLosses: data.gamelogs[0].stats.standings.losses,
            dtglWinPct: data.gamelogs[0].stats.standings.winPct,
            dtglGamesBack: data.gamelogs[0].stats.standings.gamesBack
        }
        return dailyTeamGamelogs;
    },
    seasonalPlayerStats: (data) => {
        const seasonalPlayerStats = {
            splsLastUpdatedOn: data.lastUpdatedOn,
            splsPlayerId: data.playerStatsTotals[0].player.id,
            splsPlayerFirstName: data.playerStatsTotals[0].player.firstName,
            splsPlayerLastName: data.playerStatsTotals[0].player.lastName,
            splsJerseyNumber: data.playerStatsTotals[0].player.jerseyNumber,
            splsCurrentTeamId: data.playerStatsTotals[0].player.currentTeam.id,
            splsCurrentTeamAbbreviation: data.playerStatsTotals[0].player.currentTeam.abbreviation,
            splsPlayerCurrentRosterStatus: data.playerStatsTotals[0].player.currentRosterStatus,
            splsPlayerCurrentInjury: data.playerStatsTotals[0].player.currentInjury,
            splsPlayerHeight: data.playerStatsTotals[0].player.height,
            splsPlayerWeight: data.playerStatsTotals[0].player.weight,
            splsPlayerBirthDate: data.playerStatsTotals[0].player.birthDate,
            splsPlayerAge: data.playerStatsTotals[0].player.age,
            splsPlayerBirthCity: data.playerStatsTotals[0].player.birthCity,
            splsPlayerBirthCountry: data.playerStatsTotals[0].player.birthCountry,
            splsPlayerRookie: data.playerStatsTotals[0].player.rookie,
            splsPlayerHandednessShoots: data.playerStatsTotals[0].player.handedness.shoots,
            splsPlayerOfficialImageSrc: data.playerStatsTotals[0].player.officialImageSrc,
            splsPlayerSocialMediaAccounts: data.playerStatsTotals[0].player.socialMediaAccounts,
            splsPlayerTeamId: data.playerStatsTotals[0].player.team.id,
            splsPlayerTeamAbbreviation: data.playerStatsTotals[0].player.team.abbreviation,
            splsPlayerGamesPlayed: data.playerStatsTotals[0].player.stats.gamesPlayed,
            // fields goals: seasonalPlayerStats
            splsFg2PtAtt: data.playerStatsTotals[0].stats.fieldGoals.fg2PtAtt,
            splsFg2PtAttPerGame: data.playerStatsTotals[0].stats.fieldGoals.fg2PtAttPerGame,
            splsFg2PtMade: data.playerStatsTotals[0].stats.fieldGoals.fg2PtMade,
            splsFg2PtMadePerGame: data.playerStatsTotals[0].stats.fieldGoals.fg2PtMadePerGame,
            splsFg2PtPct: data.playerStatsTotals[0].stats.fieldGoals.fg2PtPct,
            splsFg3PtAtt: data.playerStatsTotals[0].stats.fieldGoals.fg3PtAtt,
            splsFg3PtAttPerGame: data.playerStatsTotals[0].stats.fieldGoals.fg3PtAttPerGame,
            splsFg3PtMade: data.playerStatsTotals[0].stats.fieldGoals.fg3PtMade,
            splsFg3PtMadePerGame: data.playerStatsTotals[0].stats.fieldGoals.fg3PtMadePerGame,
            splsFg3PtPct: data.playerStatsTotals[0].stats.fieldGoals.fg3PtPct,
            // free throws: seasonalPlayerStats
            splsFtAtt: data.playerStatsTotals[0].stats.freeThrows.ftAtt,
            splsFtAttPerGame: data.playerStatsTotals[0].stats.freeThrows.ftAttPerGame,
            splsFtMade: data.playerStatsTotals[0].stats.freeThrows.ftMade,
            splsFtMadePerGame: data.playerStatsTotals[0].stats.freeThrows.ftMadePerGame,
            splsFtPct: data.playerStatsTotals[0].stats.freeThrows.ftPct,
            // rebounds: seasonalPlayerStats
            splsOffReb: data.playerStatsTotals[0].stats.rebounds.offReb,
            splsOffRebPerGame: data.playerStatsTotals[0].stats.rebounds.offRebPerGame,
            splsDefReb: data.playerStatsTotals[0].stats.rebounds.defReb,
            splsDefRebPerGame: data.playerStatsTotals[0].stats.rebounds.defRebPerGame,
            splsReb: data.playerStatsTotals[0].stats.rebounds.reb,
            splsRebPerGame: data.playerStatsTotals[0].stats.rebounds.rebPerGame,
            // offense: seasonalPlayerStats
            splsAst: data.playerStatsTotals[0].stats.offense.ast,
            splsAstPerGame: data.playerStatsTotals[0].stats.offense.astPerGame,
            splsPts: data.playerStatsTotals[0].stats.offense.pts,
            splsPtsPerGame: data.playerStatsTotals[0].stats.offense.ptsPerGame,
            // defense: seasonalPlayerStats
            splsTov: data.playerStatsTotals[0].stats.defense.tov,
            splsTovPerGame: data.playerStatsTotals[0].stats.defense.tovPerGame,
            splsStl: data.playerStatsTotals[0].stats.defense.stl,
            splsStlPerGame: data.playerStatsTotals[0].stats.defense.stlPerGame,
            splsBlk: data.playerStatsTotals[0].stats.defense.blk,
            splsBlkPerGame: data.playerStatsTotals[0].stats.defense.blkPerGame,
            splsBlkAgainst: data.playerStatsTotals[0].stats.defense.blkAgainst,
            splsBlkAgainstPerGame: data.playerStatsTotals[0].stats.defense.blkAgainstPerGame,
            splsFouls: data.playerStatsTotals[0].stats.miscellaneous.fouls,
            splsFoulsPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulsPerGame,
            splsFoulsDrawn: data.playerStatsTotals[0].stats.miscellaneous.foulsDrawn,
            splsFoulsDrawnPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulsDrawnPerGame,
            splsFoulsPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulPers,
            splsFoulsfoulPersPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulPersPerGame,
            splsFoulPersDrawn: data.playerStatsTotals[0].stats.miscellaneous.foulPersDrawn,
            splsFoulPersDrawnPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulPersDrawnPerGame,
            splsFoulTech: data.playerStatsTotals[0].stats.miscellaneous.foulTech,
            splsFoulTechPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulTechPerGame,
            splsFoulTechDrawn: data.playerStatsTotals[0].stats.miscellaneous.foulTechDrawn,
            splsFoulTechDrawnPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulTechDrawnPerGame,
            splsFoulFlag1: data.playerStatsTotals[0].stats.miscellaneous.foulFlag1,
            splsFoulFlag1PerGame: data.playerStatsTotals[0].stats.miscellaneous.foulFlag1PerGame,
            splsFoulFlag1Drawn: data.playerStatsTotals[0].stats.miscellaneous.foulFlag1Drawn,
            splsFoulFlag1DrawnPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulFlag1DrawnPerGame,
            splsFoulFlag2: data.playerStatsTotals[0].stats.miscellaneous.foulFlag2,
            splsFoulFlag2PerGame: data.playerStatsTotals[0].stats.miscellaneous.foulFlag2PerGame,
            splsFoulFlag2Drawn: data.playerStatsTotals[0].stats.miscellaneous.foulFlag2Drawn,
            splsFoulFlag2DrawnPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulFlag2DrawnPerGame,
            splsEjections: data.playerStatsTotals[0].stats.miscellaneous.ejections,
            splsPlusMinus: data.playerStatsTotals[0].stats.miscellaneous.plusMinus,
            splsPlusMinusPerGame: data.playerStatsTotals[0].stats.miscellaneous.plusMinusPerGame,
            splsMinSeconds: data.playerStatsTotals[0].stats.miscellaneous.minSeconds,
            splsMinSecondsPerGame: data.playerStatsTotals[0].stats.miscellaneous.minSecondsPerGame,
            splsGamesStarted: data.playerStatsTotals[0].stats.miscellaneous.gamesStarted
        }
        return seasonalPlayerStats;
    },
    seasonalTeamStats: (data) => {
        const seasonalTeamStats = {
            stmsLastUpdatedOn: data.lastUpdatedOn,
            stmsTeamId: data.teamStatsTotals[0].team.id,
            stmsTeamCity: data.teamStatsTotals[0].team.city,
            stmsTeamName: data.teamStatsTotals[0].team.name, 
            stmsTeamAbbreviation: data.teamStatsTotals[0].team.abbreviation,
            stmsTeamHomeVenueId: data.teamStatsTotals[0].team.homeVenue.id,
            stmsTeamHomeVenueName: data.teamStatsTotals[0].team.homeVenue.name,
            stmsTeamColoursHex: data.teamStatsTotals[0].team.teamColoursHex,
            stmsSocialMediaAccounts: data.teamStatsTotals[0].team.socialMediaAccounts,
            stmsOfficialLogoImageSrc: data.teamStatsTotals[0].team.officialLogoImageSrc,
            stmsGamesPlayed: data.teamStatsTotals[0].stats.gamesPlayed,
            // field goals: seasonalTeamStats
            stmsFg2PtAtt: data.teamStatsTotals[0].stats.fieldGoals.fg2PtAtt,
            stmsFg2PtAttPerGame: data.teamStatsTotals[0].stats.fieldGoals.fg2PtAttPerGame,
            stmsFg2PtMade: data.teamStatsTotals[0].stats.fieldGoals.fg2PtMade,
            stmsFg2PtMadePerGame: data.teamStatsTotals[0].stats.fieldGoals.fg2PtMadePerGame,
            stmsFg2PtPct: data.teamStatsTotals[0].stats.fieldGoals.fg2PtPct,
            stmsFg3PtAtt: data.teamStatsTotals[0].stats.fieldGoals.fg3PtAtt,
            stmsFg3PtAttPerGame: data.teamStatsTotals[0].stats.fieldGoals.fg3PtAttPerGame,
            stmsFg3PtMade: data.teamStatsTotals[0].stats.fieldGoals.fg3PtMade,
            stmsFg3PtMadePerGame: data.teamStatsTotals[0].stats.fieldGoals.fg3PtMadePerGame,
            stmsFg3PtPct: data.teamStatsTotals[0].stats.fieldGoals.fg3PtPct,
            stmsFgAtt: data.teamStatsTotals[0].stats.fieldGoals.fgAtt,
            stmsFgAttPerGame: data.teamStatsTotals[0].stats.fieldGoals.fgAttPerGame,
            stmsFgMade: data.teamStatsTotals[0].stats.fieldGoals.fgMade,
            stmsFgMadePerGame: data.teamStatsTotals[0].stats.fieldGoals.fgMadePerGame,
            stmsFgPct: data.teamStatsTotals[0].stats.fieldGoals.fgPct,
            // free throws: seasonalTeamStats
            stmsFtAtt: data.teamStatsTotals[0].stats.freeThrows.ftAtt,
            stmsFtAttPerGame: data.teamStatsTotals[0].stats.freeThrows.ftAttPerGame,
            stmsFtMade: data.teamStatsTotals[0].stats.freeThrows.ftMade,
            stmsFtMadePerGame: data.teamStatsTotals[0].stats.freeThrows.ftMadePerGame,
            stmsFtPct: data.teamStatsTotals[0].stats.freeThrows.ftPct,
            // rebounds: seasonalTeamStats
            stmsOffReb: data.teamStatsTotals[0].stats.rebounds.offReb,
            stmsOffRebPerGame: data.teamStatsTotals[0].stats.rebounds.offRebPerGame,
            stmsDefReb: data.teamStatsTotals[0].stats.rebounds.defReb,
            stmsDefRebPerGame: data.teamStatsTotals[0].stats.rebounds.defRebPerGame,
            stmsReb: data.teamStatsTotals[0].stats.rebounds.reb,
            stmsRebPerGame: data.teamStatsTotals[0].stats.rebounds.rebPerGame,
            // offense: seasonalTeamStats
            stmsAst: data.teamStatsTotals[0].stats.offense.ast,
            stmsAstPerGame: data.teamStatsTotals[0].stats.offense.astPerGame,
            stmsPts: data.teamStatsTotals[0].stats.offense.pts,
            stmsPtsPerGame: data.teamStatsTotals[0].stats.offense.ptsPerGame,
            // defense: seasonalTeamStats
            stmsTov: data.teamStatsTotals[0].stats.defense.tov,
            stmsTovPerGame: data.teamStatsTotals[0].stats.defense.tovPerGame,
            stmsStl: data.teamStatsTotals[0].stats.defense.stl,
            stmsStlPerGame: data.teamStatsTotals[0].stats.defense.stlPerGame,
            stmsBlk: data.teamStatsTotals[0].stats.defense.blk,
            stmsBlkPerGame: data.teamStatsTotals[0].stats.defense.blkPerGame,
            stmsBlkAgainst: data.teamStatsTotals[0].stats.defense.blkAgainst,
            stmsBlkAgainstPerGame: data.teamStatsTotals[0].stats.defense.blkAgainstPerGame,
            stmsPtsAgainst: data.teamStatsTotals[0].stats.defense.ptsAgainst,
            stmsPtsAgainstPerGame: data.teamStatsTotals[0].stats.defense.ptsAgainstPerGame,
            // miscellaneous: seasonalTeamStats
            stmsFouls: data.teamStatsTotals[0].stats.miscellaneous.fouls,
            stmsFoulsPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulsPerGame,
            stmsFoulsDrawn: data.teamStatsTotals[0].stats.miscellaneous.foulsDrawn,
            stmsFoulsDrawnPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulsDrawnPerGame,
            stmsFoulPers: data.teamStatsTotals[0].stats.miscellaneous.foulPers,
            stmsFoulPersPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulPersPerGame,
            stmsFoulPersDrawn: data.teamStatsTotals[0].stats.miscellaneous.foulPersDrawn,
            stmsFoulPersDrawnPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulPersDrawnPerGame,
            stmsFoulTech: data.teamStatsTotals[0].stats.miscellaneous.foulTech,
            stmsFoulTechPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulTechPerGame,
            stmsFoulTechDrawn: data.teamStatsTotals[0].stats.miscellaneous.foulTechDrawn,
            stmsFoulTechDrawnPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulTechDrawnPerGame,
            stmsFoulFlag1: data.teamStatsTotals[0].stats.miscellaneous.foulFlag1,
            stmsFoulFlag1PerGame: data.teamStatsTotals[0].stats.miscellaneous.foulFlag1PerGame,
            stmsFoulFlag1Drawn: data.teamStatsTotals[0].stats.miscellaneous.foulFlag1Drawn,
            stmsFoulFlag1DrawnPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulFlag1DrawnPerGame,
            stmsFoulFlag2: data.teamStatsTotals[0].stats.miscellaneous.foulFlag2,
            stmsFoulFlag2PerGame: data.teamStatsTotals[0].stats.miscellaneous.foulFlag2PerGame,
            stmsFoulFlag2Drawn: data.teamStatsTotals[0].stats.miscellaneous.foulFlag2Drawn,
            stmsFoulFlag2DrawnPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulFlag2DrawnPerGame,
            stmsEjections: data.teamStatsTotals[0].stats.miscellaneous.ejections,
            stmsPlusMinus: data.teamStatsTotals[0].stats.miscellaneous.plusMinus,
            stmsPlusMinusPerGame : data.teamStatsTotals[0].stats.miscellaneous.plusMinusPerGame,
            // standings: seasonalTeamStats
            stmsWins: data.teamStatsTotals[0].stats.standings.wins,
            stmsLosses: data.teamStatsTotals[0].stats.standings.losses,
            stmsWinPct: data.teamStatsTotals[0].stats.standings.winPct,
            stmsGamesBack: data.teamStatsTotals[0].stats.standings.gamesBack
        }
        return seasonalTeamStats;
    }
}


module.exports = API;