
const API = {
    players: (data) => {
        let playersArray = [];
        data.players.forEach(item => {
            const player = {
                plyrLastUpdatedOn: data.lastUpdatedOn ? data.lastUpdatedOn : undefined,
                plyrId: item.player.id ? item.player.id : undefined,
                plyrFirstName: item.player.firstName ? item.player.firstName : undefined,
                plyrLastName: item.player.lastName ? item.player.lastName : undefined,
                plyrPrimaryPosition: item.player.primaryPosition ? item.player.primaryPosition : undefined,
                plyrAlternatePositions: item.player.alternatePositions ? item.player.alternatePositions : undefined,
                plyrJerseyNumber: item.player.jerseyNumber ? item.player.jerseyNumber : undefined,
                plyrCurrentTeamId: item.player.currentTeam.id ? item.player.currentTeam.id : undefined,
                plyrCurrentTeamAbbreviation: item.player.currentTeam.abbreviation ? item.player.currentTeam.abbreviation : undefined,
                plyrCurrentRosterStatus: item.player.currentRosterStatus ? item.player.currentRosterStatus : undefined,
                plyrCurrentInjury: item.player.currentInjury ? item.player.currentInjury : undefined,
                plyrHeight: item.player.height ? item.player.height : undefined,
                plyrWeight: item.player.weight ? item.player.weight : undefined,
                plyrBirthDate: item.player.birthDate ? item.player.birthDate : undefined,
                plyrAge: item.player.age ? item.player.age : undefined,
                plyrBirthCity: item.player.birthCity ? item.player.birthCity : undefined,
                plyrBirthCountry: item.player.birthCountry ? item.player.birthCountry : undefined,
                plyrRookie: item.player.rookie ? item.player.rookie : undefined,
                plyrHighSchool: item.player.highSchool ? item.player.highSchool : undefined,
                plyrCollege: item.player.college ? item.player.college : undefined,
                plyrOfficialImageSrc: item.player.officialImageSrc ? item.player.officialImageSrc : undefined,
                
                plyrHandednessShoots: (item.player.handedness && item.player.handedness.shoots) ? item.player.handedness.shoots : undefined,
                plyrSocialMediaType: (item.player.socialMediaAccounts && item.player.socialMediaAccounts[0].mediaType) ? item.player.socialMediaAccounts[0].mediaType : undefined,
                plyrSocialMediaValue: (item.player.socialMediaAccounts && item.player.socialMediaAccounts[0].value) ? item.player.socialMediaAccounts[0].value : undefined,
                
                plyrContractStartYear: (item.player.currentContractYear && item.player.currentContractYear.seasonStartYear) ? item.player.currentContractYear.seasonStartYear : undefined,
                plyrContractBaseSalary: (item.player.currentContractYear && item.player.currentContractYear.baseSalary) ? item.player.currentContractYear.baseSalary : undefined,
                plyrContractMinorsSalary: (item.player.currentContractYear && item.player.currentContractYear.minorsSalary) ? item.player.currentContractYear.minorsSalary : undefined,
                plyrContractSigningBonus: (item.player.currentContractYear && item.player.currentContractYear.signingBonus) ? item.player.currentContractYear.signingBonus : undefined,
                plyrContractOtherBonuses: (item.player.currentContractYear && item.player.currentContractYear.otherBonuses) ? item.player.currentContractYear.otherBonuses : undefined,
                plyrContractCapHit: (item.player.currentContractYear && item.player.currentContractYear.capHit) ? item.player.currentContractYear.capHit : undefined,
                plyrContractNoTradeClause: (item.player.currentContractYear && item.player.currentContractYear.fullNoTradeClause) ? item.player.currentContractYear.fullNoTradeClause : undefined,
                plyrContractModifiedTradeClause: (item.player.currentContractYear && item.player.currentContractYear.modifiedNoTradeClause) ? item.player.currentContractYear.modifiedNoTradeClause : undefined,
                plyrContractnoMovementClause: (item.player.currentContractYear && item.player.currentContractYear.noMovementClause) ? item.player.currentContractYear.noMovementClause : undefined,
                plyrContractSigningTeamId: (item.player.currentContractYear && item.player.currentContractYear.overallContract.signingTeam.id) ? item.player.currentContractYear.overallContract.signingTeam.id : undefined,
                plyrContractSigningTeamAbbreviation: (item.player.currentContractYear && item.player.currentContractYear.overallContract.signingTeam.abbreviation) ? item.player.currentContractYear.overallContract.signingTeam.abbreviation : undefined,
                plyrContractSignedOn: (item.player.currentContractYear && item.player.currentContractYear.overallContract.signedOn) ? item.player.currentContractYear.overallContract.signedOn : undefined,
                plyrContractTotalYears: (item.player.currentContractYear && item.player.currentContractYear.overallContract.totalYears) ? item.player.currentContractYear.overallContract.totalYears : undefined,
                plyrContractTotalSalary: (item.player.currentContractYear && item.player.currentContractYear.overallContract.totalSalary) ? item.player.currentContractYear.overallContract.totalSalary : undefined,
                plyrContractTotalBonuses: (item.player.currentContractYear && item.player.currentContractYear.overallContract.totalBonuses) ? item.player.currentContractYear.overallContract.totalBonuses : undefined,
                plyrContractExpiryStatus: (item.player.currentContractYear && item.player.currentContractYear.overallContract.expiryStatus) ? item.player.currentContractYear.overallContract.expiryStatus : undefined,
                plyrContractAnnualSalary: (item.player.currentContractYear && item.player.currentContractYear.overallContract.annualAverageSalary) ? item.player.currentContractYear.overallContract.annualAverageSalary : undefined,
                
                plyrDraftedYear: (item.player.drafted && item.player.drafted.year) ? item.player.drafted.year : undefined,
                plyrDraftedTeamId: (item.player.drafted && item.player.drafted.team.id) ? item.player.drafted.team.id : undefined,
                plyrDraftedTeamAbbreviation: (item.player.drafted && item.player.drafted.team.abbreviation) ? item.player.drafted.team.abbreviation : undefined,
                plyrDraftedPickTeamId: (item.player.drafted && item.player.drafted.pickTeam.id) ? item.player.drafted.pickTeam.id : undefined,
                plyrDraftedPickTeamAbbreviation: (item.player.drafted && item.player.drafted.pickTeam.abbreviation) ? item.player.drafted.pickTeam.abbreviation : undefined,
                plyrDraftedRound: (item.player.drafted && item.player.drafted.round) ? item.player.drafted.round : undefined,
                plyrDraftedRoundPick: (item.player.drafted && item.player.drafted.roundPick) ? item.player.drafted.roundPick : undefined,
                plyrOverallPick: (item.player.drafted && item.player.drafted.overallPick) ? item.player.drafted.overallPick : undefined,
                
                plyrExternalMappingsSource: (item.player.externalMappings && item.player.externalMappings[0].source) ? item.player.externalMappings[0].source : undefined,
                plyrExternalMappingsId: (item.player.externalMappings && item.player.externalMappings[0].id) ? item.player.externalMappings[0].id : undefined,
                plyrTeamAsOfDateId: (item.teamAsOfDate && item.teamAsOfDate.id) ? item.teamAsOfDate.id : undefined,
                plyrTeamAsOfDateAbbreviation: (item.teamAsOfDate && item.teamAsOfDate.abbreviatio) ? item.teamAsOfDate.abbreviatio : undefined
            }
            playersArray.push(player)
        })
        return playersArray;
    },
    playerInjuries: (data) => {
        const playerInjuries = {
            plijLastUpdatedOn: data.lastUpdatedOn,
            plijId: data.players[0].id,
            plijFirstName: data.players[0].firstName,
            plijLastName: data.players[0].lastName,
            plijPrimaryPosition: data.players[0].primaryPosition,
            plijJerseyNumber: data.players[0].jerseyNumber,
            plijCurrentTeamId: data.players[0].currentTeam.id,
            plijCurrentTeamAbbreviation: data.players[0].currentTeam.abbreviation,
            plijCurrentRosterStatus: data.players[0].currentRosterStatus,
            plijCurrentInjuries: data.players[0].currentInjuries,
            plijCurrentInjuryDescription: data.players[0].currentInjury.description,
            plijCurrentInjuryPlayingProbability: data.players[0].currentInjury.playingProbability,
            plijHeight: data.players[0].height,
            plijWeight: data.players[0].weight,
            plijBirthDate: data.players[0].birthDate,
            plijAge: data.players[0].age,
            plijBirthCity: data.players[0].birthCity,
            plijHighSchool: data.players[0].highSchool,
            plijCollege: data.players[0].college,
            plijHandednessShoots: data.players[0].shoots,
            plijOfficialImageSrc: data.players[0].officialImageSrc,
            plijSocialMediaAccountsMediaType: data.players[0].mediaTypes,
            plijSocialMediaAccountsValue: data.players[0].value
        }
        return playerInjuries;
    },
    dailyPlayerGameLogs: (data) => {
        const dailyPlayerGameLogs = {
            dpglLatestUpdatedOn: data.lastUpdatedOn,
            dpglGameId: data.gamelogs[0].game.id,
            dpglGameStartTime: data.gamelogs[0].game.startTime,
            dpglGamesAwayTeamAbbreviation: data.gamelogs[0].game.awayTeamAbbreviation,
            dpglGamesHomeTeamAbbreviation: data.gamelogs[0].game.homeTeamAbbreviation,
            dpglPlayerId: data.gamelogs[0].player.id,
            dpglPlayerFirstName: data.gamelogs[0].player.firstName,
            dpglPlayerLastName: data.gamelogs[0].player.lastName,
            dpglPlayerPosition: data.gamelogs[0].player.position,
            dpglPlayerJerseyNumber: data.gamelogs[0].player.jerseyNumber,
            dpglTeamId: data.gamelogs[0].team.id,
            dpglTeamAbbreviation: data.gamelogs[0].team.abbreviation,
            dpglFg2PtAtt: data.gamelogs[0].stats.fieldGoals.fg2PtAtt,
            dpglFg2PtAttPerGame: data.gamelogs[0].stats.fieldGoals.fg2PtAttPerGame,
            dpglFg2PtMade: data.gamelogs[0].stats.fieldGoals.fg2PtMade,  
            dpglFg2PtMadePerGame: data.gamelogs[0].stats.fieldGoals.fg2PtMadePerGame,
            dpglFg2PtPct: data.gamelogs[0].stats.fieldGoals.fg2PtPct,
            dpglFg3PtAtt: data.gamelogs[0].stats.fieldGoals.fg3PtAtt,
            dpglFg3PtAttPerGame: data.gamelogs[0].stats.fieldGoals.fg3PtAttPerGame,
            dpglFg3PtMade: data.gamelogs[0].stats.fieldGoals.fg3PtMade,
            dpglFg3PtMadePerGame: data.gamelogs[0].stats.fieldGoals.fg3PtMadePerGame,
            dpglFg3PtPct: data.gamelogs[0].stats.fieldGoals.fg3PtPct,
            dpglFgAtt: data.gamelogs[0].stats.fieldGoals.fgAtt,
            dpglFgAttPerGame: data.gamelogs[0].stats.fieldGoals.fgAttPerGame,
            dpglFgMade: data.gamelogs[0].stats.fieldGoals.fgMade,
            dpglFgMadePerGame: data.gamelogs[0].stats.fieldGoals.fgMadePerGame,
            dpglFgPct: data.gamelogs[0].stats.fieldGoals.fgPct,
            dpglFtAtt: data.gamelogs[0].stats.freeThrows.ftAtt,
            dpglFtAttPerGame: data.gamelogs[0].stats.freeThrows.ftAttPerGame,
            dpglFtMade: data.gamelogs[0].stats.freeThrows.ftMade,
            dpglFtMadePerGame: data.gamelogs[0].stats.freeThrows.ftMadePerGame,
            dpglFtPct: data.gamelogs[0].stats.freeThrows.ftPct,
            dpglOffReb: data.gamelogs[0].stats.rebounds.offReb,
            dpglOffRebPerGame: data.gamelogs[0].stats.rebounds.offRebPerGame,
            dpglDefReb: data.gamelogs[0].stats.rebounds.defReb,
            dpglDefRebPerGame: data.gamelogs[0].stats.rebounds.defRebPerGame,
            dpglReb: data.gamelogs[0].stats.rebounds.reb,
            dpglRebPerGame: data.gamelogs[0].stats.rebounds.rebPerGame,
            dpglAst: data.gamelogs[0].stats.offense.ast,
            dpglAstPerGame: data.gamelogs[0].stats.offense.astPerGame,
            dpglPts: data.gamelogs[0].stats.offense.pts,
            dpglPtsPerGame: data.gamelogs[0].stats.offense.ptsPerGame,
            dpglTov: data.gamelogs[0].stats.defense.tov,
            dpglTovPerGame: data.gamelogs[0].stats.defense.tovPerGame,
            dpglStl: data.gamelogs[0].stats.defense.stl,
            dpglStlPerGame: data.gamelogs[0].stats.defense.stlPerGame,
            dpglBlk: data.gamelogs[0].stats.defense.blk,
            dpglBlkPerGame: data.gamelogs[0].stats.defense.blkPerGame,
            dpglBlkAgainst: data.gamelogs[0].stats.defense.blkAgainst,
            dpglBlkAgainstPerGame: data.gamelogs[0].stats.defense.blkAgainstPerGame,
            // miscelleneous: dailyPlayerGameLogs
            dpglFouls: data.gamelogs[0].stats.miscellaneous.fouls,
            dpglFoulsPerGame: data.gamelogs[0].stats.miscellaneous.foulsPerGame,
            dpglFoulsDrawn: data.gamelogs[0].stats.miscellaneous.foulsDrawn,
            dpglFoulsDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulsDrawnPerGame,
            dpglFoulPers: data.gamelogs[0].stats.miscellaneous.foulPers,
            dpglFoulPersPerGame: data.gamelogs[0].stats.miscellaneous.foulPersPerGame,
            dpglFoulPersDrawn: data.gamelogs[0].stats.miscellaneous.foulPersDrawn,
            dpglFoulPersDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulPersDrawnPerGame,
    
            dpglFoulTech: data.gamelogs[0].stats.miscellaneous.foulTech,
            dpglFoulTechPerGame: data.gamelogs[0].stats.miscellaneous.foulTechPerGame,
            dpglFoulTechDrawn: data.gamelogs[0].stats.miscellaneous.foulTechDrawn,
            dpglFoulTechDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulTechDrawnPerGame,
            dpglFoulFlag1: data.gamelogs[0].stats.miscellaneous.foulFlag1,
            dpglFoulFlag1PerGame: data.gamelogs[0].stats.miscellaneous.foulFlag1PerGame,
            dpglFoulFlag1Drawn: data.gamelogs[0].stats.miscellaneous.foulFlag1Drawn,
            dpglFoulFlag1DrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulFlag1DrawnPerGame,
            dpglFoulFlag2: data.gamelogs[0].stats.miscellaneous.foulFlag2,
            dpglFoulFlag2PerGame: data.gamelogs[0].stats.miscellaneous.foulFlag2PerGame,
            dpglFoulFlage2Drawn: data.gamelogs[0].stats.miscellaneous.foulFlag2Drawn,
            dpglFoulFlag2DrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulFlag2DrawnPerGame,
        
            dpglEjections: data.gamelogs[0].stats.miscellaneous.ejections,
            dpglPlusMinus: data.gamelogs[0].stats.miscellaneous.plusMinus,
            dpglPlusMInusPerGame: data.gamelogs[0].stats.miscellaneous.plusMinusPerGame,
            dpglMinSeconds: data.gamelogs[0].stats.miscellaneous.minSeconds,
            dpglMinSecondsPerGame: data.gamelogs[0].stats.miscellaneous.minSecondsPerGame,
            dpglGamesStarted: data.gamelogs[0].stats.miscellaneous.gamesStarted
        }
        return dailyPlayerGameLogs;
    },
    dailyTeamGamelogs: (data) => {
        const dailyTeamGamelogs = {
            dtglLastUpdatedOn: data.lastUpdatedOn,
            dtglGameId: data.gamelogs[0].game.id,
            dtglGameStartTime: data.gamelogs[0].game.startTime,
            dtglGameAwayTeamAbbreviation: data.gamelogs[0].game.awayTeamAbbreviation,
            dtglGameHomeTeamAbbreviation: data.gamelogs[0].game.homeTeamAbbreviation,
            dtglTeamId: data.gamelogs[0].team.id,
            dtglTeamAbbreviation: data.gamelogs[0].team.abbreviation,
            // 2pt field goals: dailyTeamGameLogs
            dtglFg2PtAtt: data.gamelogs[0].stats.fieldGoals.fg2PtAtt,
            dtglFg2PtAttPerGame: data.gamelogs[0].stats.fieldGoals.fg2PtAttPerGame,
            dtglFg2PtMade: data.gamelogs[0].stats.fieldGoals.fg2PtMade,
            dtglFg2PtMadePerGame: data.gamelogs[0].stats.fieldGoals.fg2PtMadePerGame,
            dtglFg2PtPct: data.gamelogs[0].stats.fieldGoals.fg2PtPct,
            // 3pt field goals: dailyTeamGameLogs
            dtglFg3PtAtt: data.gamelogs[0].stats.fieldGoals.fg3PtAtt,
            dtglFg3PtAttPerGame: data.gamelogs[0].stats.fieldGoals.fg3PtAttPerGame,
            dtglFg3PtMade: data.gamelogs[0].stats.fieldGoals.fg3PtMade,
            dtglFg3PtMadePerGame: data.gamelogs[0].stats.fieldGoals.fg3PtMadePerGame,
            dtglFg3PtPct: data.gamelogs[0].stats.fieldGoals.fg3PtPct,
            // total field goals: dailyTeamGameLogs
            dtglFgAtt: data.gamelogs[0].stats.fieldGoals.fgAtt,
            dtglFgAttPerGame: data.gamelogs[0].stats.fieldGoals.fgAttPerGame,
            dtglFgMade: data.gamelogs[0].stats.fieldGoals.fgMade,
            dtglFgMadePerGame: data.gamelogs[0].stats.fieldGoals.fgMadePerGame,
            dtglFgPct: data.gamelogs[0].stats.fieldGoals.fgPct,
            // free throws: dailyTeamGameLogs
            dtglFtAtt: data.gamelogs[0].stats.freeThrows.ftAtt,
            dtglFtAttPerGame: data.gamelogs[0].stats.freeThrows.ftAttPerGame,
            dtglFtMade: data.gamelogs[0].stats.freeThrows.ftMade,
            dtglFtMadePerGame: data.gamelogs[0].stats.freeThrows.ftMadePerGame,
            dtglFtPct: data.gamelogs[0].stats.freeThrows.ftPct,
            // rebounds: dailyTeamGameLogs
            dtglOffReb: data.gamelogs[0].stats.rebounds.offReb,
            dtglOffRebPerGame: data.gamelogs[0].stats.rebounds.offRebPerGame,
            dtglDefReb: data.gamelogs[0].stats.rebounds.defReb,
            dtglDefRebPerGame: data.gamelogs[0].stats.rebounds.defRebPerGame,
            dtglReb: data.gamelogs[0].stats.rebounds.reb,
            dtglRebPerGame: data.gamelogs[0].stats.rebounds.rebPerGame,
            // offense: dailyTeamGameLogs
            dtglAst: data.gamelogs[0].stats.offense.ast,
            dtglAstPerGame: data.gamelogs[0].stats.offense.astPerGame,
            dtglPts: data.gamelogs[0].stats.offense.pts,
            dtglPtsPerGame: data.gamelogs[0].stats.offense.ptsPerGame,
            // defense: dailyTeamGameLogs
            dtglTov: data.gamelogs[0].stats.defense.tov,
            dtglTovPerGame: data.gamelogs[0].stats.defense.tovPerGame,
            dtglStl: data.gamelogs[0].stats.defense.stl,
            dtglStlPerGame: data.gamelogs[0].stats.defense.stlPerGame,
            dtglBlk: data.gamelogs[0].stats.defense.blk,
            dtglBlkPerGame: data.gamelogs[0].stats.defense.blkPerGame,
            dtglBlkAgainst: data.gamelogs[0].stats.defense.blkAgainst,
            dtglBlkAgainstPerGame: data.gamelogs[0].stats.defense.blkAgainstPerGame,
            dtglPtsAgainst: data.gamelogs[0].stats.defense.ptsAgainst,
            dtglPtsAgainstPerGame: data.gamelogs[0].stats.defense.ptsAgainstPerGame,
            // miscellaneous: dailyTeamGameLogs
            dtglFouls: data.gamelogs[0].stats.miscellaneous.fouls,
            dtglFoulsPerGame: data.gamelogs[0].stats.miscellaneous.foulsPerGame,
            dtglFoulsDrawn: data.gamelogs[0].stats.miscellaneous.foulsDrawn,
            dtglFoulsDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulsDrawnPerGame,
            dtglFoulPers: data.gamelogs[0].stats.miscellaneous.foulPers,
            dtglFoulPersPerGame: data.gamelogs[0].stats.miscellaneous.foulPersPerGame,
            dtglFoulPersDrawn: data.gamelogs[0].stats.miscellaneous.foulPersDrawn,
            dtglFoulPersDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulPersDrawnPerGame,
            dtglFoulTech: data.gamelogs[0].stats.miscellaneous.foulTech,
            dtglFoulTechPerGame: data.gamelogs[0].stats.miscellaneous.foulTechPerGame,
            dtglFoulTechDrawn: data.gamelogs[0].stats.miscellaneous.foulTechDrawn,
            dtglFoulTechDrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulTechDrawnPerGame,
            dtglFoulFlag1: data.gamelogs[0].stats.miscellaneous.foulFlag1,
            dtglFoulFlag1PerGame: data.gamelogs[0].stats.miscellaneous.foulFlag1PerGame,
            dtglFoulFlag1Drawn: data.gamelogs[0].stats.miscellaneous.foulFlag1Drawn,
            dtglFoulFlag1DrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulFlag1DrawnPerGame,
            dtglFoulFlag2: data.gamelogs[0].stats.miscellaneous.foulFlag2,
            dtglFoulFlag2PerGame: data.gamelogs[0].stats.miscellaneous.foulFlag2PerGame,
            dtglFoulFlag2Drawn: data.gamelogs[0].stats.miscellaneous.foulFlag2Drawn,
            dtglFoulFlag2DrawnPerGame: data.gamelogs[0].stats.miscellaneous.foulFlag2DrawnPerGame,
            dtglEjections: data.gamelogs[0].stats.miscellaneous.ejections,
            dtglPlusMinus: data.gamelogs[0].stats.miscellaneous.plusMinus,
            dtglPlusMinusPerGame: data.gamelogs[0].stats.miscellaneous.plusMinusPerGame,
            // standings: dailyTeamGameLogs
            dtglWins: data.gamelogs[0].stats.standings.wins,
            dtglLosses: data.gamelogs[0].stats.standings.losses,
            dtglWinPct: data.gamelogs[0].stats.standings.winPct,
            dtglGamesBack: data.gamelogs[0].stats.standings.gamesBack
        }
        return dailyTeamGamelogs;
    },
    seasonalPlayerStats: (data) => {
        const seasonalPlayerStats = {
            splsLastUpdatedOn: data.lastUpdatedOn,
            splsPlayerId: data.playerStatsTotals[0].player.id,
            splsPlayerFirstName: data.playerStatsTotals[0].player.firstName,
            splsPlayerLastName: data.playerStatsTotals[0].player.lastName,
            splsJerseyNumber: data.playerStatsTotals[0].player.jerseyNumber,
            splsCurrentTeamId: data.playerStatsTotals[0].player.currentTeam.id,
            splsCurrentTeamAbbreviation: data.playerStatsTotals[0].player.currentTeam.abbreviation,
            splsPlayerCurrentRosterStatus: data.playerStatsTotals[0].player.currentRosterStatus,
            splsPlayerCurrentInjury: data.playerStatsTotals[0].player.currentInjury,
            splsPlayerHeight: data.playerStatsTotals[0].player.height,
            splsPlayerWeight: data.playerStatsTotals[0].player.weight,
            splsPlayerBirthDate: data.playerStatsTotals[0].player.birthDate,
            splsPlayerAge: data.playerStatsTotals[0].player.age,
            splsPlayerBirthCity: data.playerStatsTotals[0].player.birthCity,
            splsPlayerBirthCountry: data.playerStatsTotals[0].player.birthCountry,
            splsPlayerRookie: data.playerStatsTotals[0].player.rookie,
            splsPlayerHandednessShoots: data.playerStatsTotals[0].player.handedness.shoots,
            splsPlayerOfficialImageSrc: data.playerStatsTotals[0].player.officialImageSrc,
            splsPlayerSocialMediaAccounts: data.playerStatsTotals[0].player.socialMediaAccounts,
            splsPlayerTeamId: data.playerStatsTotals[0].player.team.id,
            splsPlayerTeamAbbreviation: data.playerStatsTotals[0].player.team.abbreviation,
            splsPlayerGamesPlayed: data.playerStatsTotals[0].player.stats.gamesPlayed,
            // fields goals: seasonalPlayerStats
            splsFg2PtAtt: data.playerStatsTotals[0].stats.fieldGoals.fg2PtAtt,
            splsFg2PtAttPerGame: data.playerStatsTotals[0].stats.fieldGoals.fg2PtAttPerGame,
            splsFg2PtMade: data.playerStatsTotals[0].stats.fieldGoals.fg2PtMade,
            splsFg2PtMadePerGame: data.playerStatsTotals[0].stats.fieldGoals.fg2PtMadePerGame,
            splsFg2PtPct: data.playerStatsTotals[0].stats.fieldGoals.fg2PtPct,
            splsFg3PtAtt: data.playerStatsTotals[0].stats.fieldGoals.fg3PtAtt,
            splsFg3PtAttPerGame: data.playerStatsTotals[0].stats.fieldGoals.fg3PtAttPerGame,
            splsFg3PtMade: data.playerStatsTotals[0].stats.fieldGoals.fg3PtMade,
            splsFg3PtMadePerGame: data.playerStatsTotals[0].stats.fieldGoals.fg3PtMadePerGame,
            splsFg3PtPct: data.playerStatsTotals[0].stats.fieldGoals.fg3PtPct,
            // free throws: seasonalPlayerStats
            splsFtAtt: data.playerStatsTotals[0].stats.freeThrows.ftAtt,
            splsFtAttPerGame: data.playerStatsTotals[0].stats.freeThrows.ftAttPerGame,
            splsFtMade: data.playerStatsTotals[0].stats.freeThrows.ftMade,
            splsFtMadePerGame: data.playerStatsTotals[0].stats.freeThrows.ftMadePerGame,
            splsFtPct: data.playerStatsTotals[0].stats.freeThrows.ftPct,
            // rebounds: seasonalPlayerStats
            splsOffReb: data.playerStatsTotals[0].stats.rebounds.offReb,
            splsOffRebPerGame: data.playerStatsTotals[0].stats.rebounds.offRebPerGame,
            splsDefReb: data.playerStatsTotals[0].stats.rebounds.defReb,
            splsDefRebPerGame: data.playerStatsTotals[0].stats.rebounds.defRebPerGame,
            splsReb: data.playerStatsTotals[0].stats.rebounds.reb,
            splsRebPerGame: data.playerStatsTotals[0].stats.rebounds.rebPerGame,
            // offense: seasonalPlayerStats
            splsAst: data.playerStatsTotals[0].stats.offense.ast,
            splsAstPerGame: data.playerStatsTotals[0].stats.offense.astPerGame,
            splsPts: data.playerStatsTotals[0].stats.offense.pts,
            splsPtsPerGame: data.playerStatsTotals[0].stats.offense.ptsPerGame,
            // defense: seasonalPlayerStats
            splsTov: data.playerStatsTotals[0].stats.defense.tov,
            splsTovPerGame: data.playerStatsTotals[0].stats.defense.tovPerGame,
            splsStl: data.playerStatsTotals[0].stats.defense.stl,
            splsStlPerGame: data.playerStatsTotals[0].stats.defense.stlPerGame,
            splsBlk: data.playerStatsTotals[0].stats.defense.blk,
            splsBlkPerGame: data.playerStatsTotals[0].stats.defense.blkPerGame,
            splsBlkAgainst: data.playerStatsTotals[0].stats.defense.blkAgainst,
            splsBlkAgainstPerGame: data.playerStatsTotals[0].stats.defense.blkAgainstPerGame,
            splsFouls: data.playerStatsTotals[0].stats.miscellaneous.fouls,
            splsFoulsPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulsPerGame,
            splsFoulsDrawn: data.playerStatsTotals[0].stats.miscellaneous.foulsDrawn,
            splsFoulsDrawnPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulsDrawnPerGame,
            splsFoulsPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulPers,
            splsFoulsfoulPersPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulPersPerGame,
            splsFoulPersDrawn: data.playerStatsTotals[0].stats.miscellaneous.foulPersDrawn,
            splsFoulPersDrawnPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulPersDrawnPerGame,
            splsFoulTech: data.playerStatsTotals[0].stats.miscellaneous.foulTech,
            splsFoulTechPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulTechPerGame,
            splsFoulTechDrawn: data.playerStatsTotals[0].stats.miscellaneous.foulTechDrawn,
            splsFoulTechDrawnPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulTechDrawnPerGame,
            splsFoulFlag1: data.playerStatsTotals[0].stats.miscellaneous.foulFlag1,
            splsFoulFlag1PerGame: data.playerStatsTotals[0].stats.miscellaneous.foulFlag1PerGame,
            splsFoulFlag1Drawn: data.playerStatsTotals[0].stats.miscellaneous.foulFlag1Drawn,
            splsFoulFlag1DrawnPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulFlag1DrawnPerGame,
            splsFoulFlag2: data.playerStatsTotals[0].stats.miscellaneous.foulFlag2,
            splsFoulFlag2PerGame: data.playerStatsTotals[0].stats.miscellaneous.foulFlag2PerGame,
            splsFoulFlag2Drawn: data.playerStatsTotals[0].stats.miscellaneous.foulFlag2Drawn,
            splsFoulFlag2DrawnPerGame: data.playerStatsTotals[0].stats.miscellaneous.foulFlag2DrawnPerGame,
            splsEjections: data.playerStatsTotals[0].stats.miscellaneous.ejections,
            splsPlusMinus: data.playerStatsTotals[0].stats.miscellaneous.plusMinus,
            splsPlusMinusPerGame: data.playerStatsTotals[0].stats.miscellaneous.plusMinusPerGame,
            splsMinSeconds: data.playerStatsTotals[0].stats.miscellaneous.minSeconds,
            splsMinSecondsPerGame: data.playerStatsTotals[0].stats.miscellaneous.minSecondsPerGame,
            splsGamesStarted: data.playerStatsTotals[0].stats.miscellaneous.gamesStarted
        }
        return seasonalPlayerStats;
    },
    seasonalTeamStats: (data) => {
        const seasonalTeamStats = {
            stmsLastUpdatedOn: data.lastUpdatedOn,
            stmsTeamId: data.teamStatsTotals[0].team.id,
            stmsTeamCity: data.teamStatsTotals[0].team.city,
            stmsTeamName: data.teamStatsTotals[0].team.name, 
            stmsTeamAbbreviation: data.teamStatsTotals[0].team.abbreviation,
            stmsTeamHomeVenueId: data.teamStatsTotals[0].team.homeVenue.id,
            stmsTeamHomeVenueName: data.teamStatsTotals[0].team.homeVenue.name,
            stmsTeamColoursHex: data.teamStatsTotals[0].team.teamColoursHex,
            stmsSocialMediaAccounts: data.teamStatsTotals[0].team.socialMediaAccounts,
            stmsOfficialLogoImageSrc: data.teamStatsTotals[0].team.officialLogoImageSrc,
            stmsGamesPlayed: data.teamStatsTotals[0].stats.gamesPlayed,
            // field goals: seasonalTeamStats
            stmsFg2PtAtt: data.teamStatsTotals[0].stats.fieldGoals.fg2PtAtt,
            stmsFg2PtAttPerGame: data.teamStatsTotals[0].stats.fieldGoals.fg2PtAttPerGame,
            stmsFg2PtMade: data.teamStatsTotals[0].stats.fieldGoals.fg2PtMade,
            stmsFg2PtMadePerGame: data.teamStatsTotals[0].stats.fieldGoals.fg2PtMadePerGame,
            stmsFg2PtPct: data.teamStatsTotals[0].stats.fieldGoals.fg2PtPct,
            stmsFg3PtAtt: data.teamStatsTotals[0].stats.fieldGoals.fg3PtAtt,
            stmsFg3PtAttPerGame: data.teamStatsTotals[0].stats.fieldGoals.fg3PtAttPerGame,
            stmsFg3PtMade: data.teamStatsTotals[0].stats.fieldGoals.fg3PtMade,
            stmsFg3PtMadePerGame: data.teamStatsTotals[0].stats.fieldGoals.fg3PtMadePerGame,
            stmsFg3PtPct: data.teamStatsTotals[0].stats.fieldGoals.fg3PtPct,
            stmsFgAtt: data.teamStatsTotals[0].stats.fieldGoals.fgAtt,
            stmsFgAttPerGame: data.teamStatsTotals[0].stats.fieldGoals.fgAttPerGame,
            stmsFgMade: data.teamStatsTotals[0].stats.fieldGoals.fgMade,
            stmsFgMadePerGame: data.teamStatsTotals[0].stats.fieldGoals.fgMadePerGame,
            stmsFgPct: data.teamStatsTotals[0].stats.fieldGoals.fgPct,
            // free throws: seasonalTeamStats
            stmsFtAtt: data.teamStatsTotals[0].stats.freeThrows.ftAtt,
            stmsFtAttPerGame: data.teamStatsTotals[0].stats.freeThrows.ftAttPerGame,
            stmsFtMade: data.teamStatsTotals[0].stats.freeThrows.ftMade,
            stmsFtMadePerGame: data.teamStatsTotals[0].stats.freeThrows.ftMadePerGame,
            stmsFtPct: data.teamStatsTotals[0].stats.freeThrows.ftPct,
            // rebounds: seasonalTeamStats
            stmsOffReb: data.teamStatsTotals[0].stats.rebounds.offReb,
            stmsOffRebPerGame: data.teamStatsTotals[0].stats.rebounds.offRebPerGame,
            stmsDefReb: data.teamStatsTotals[0].stats.rebounds.defReb,
            stmsDefRebPerGame: data.teamStatsTotals[0].stats.rebounds.defRebPerGame,
            stmsReb: data.teamStatsTotals[0].stats.rebounds.reb,
            stmsRebPerGame: data.teamStatsTotals[0].stats.rebounds.rebPerGame,
            // offense: seasonalTeamStats
            stmsAst: data.teamStatsTotals[0].stats.offense.ast,
            stmsAstPerGame: data.teamStatsTotals[0].stats.offense.astPerGame,
            stmsPts: data.teamStatsTotals[0].stats.offense.pts,
            stmsPtsPerGame: data.teamStatsTotals[0].stats.offense.ptsPerGame,
            // defense: seasonalTeamStats
            stmsTov: data.teamStatsTotals[0].stats.defense.tov,
            stmsTovPerGame: data.teamStatsTotals[0].stats.defense.tovPerGame,
            stmsStl: data.teamStatsTotals[0].stats.defense.stl,
            stmsStlPerGame: data.teamStatsTotals[0].stats.defense.stlPerGame,
            stmsBlk: data.teamStatsTotals[0].stats.defense.blk,
            stmsBlkPerGame: data.teamStatsTotals[0].stats.defense.blkPerGame,
            stmsBlkAgainst: data.teamStatsTotals[0].stats.defense.blkAgainst,
            stmsBlkAgainstPerGame: data.teamStatsTotals[0].stats.defense.blkAgainstPerGame,
            stmsPtsAgainst: data.teamStatsTotals[0].stats.defense.ptsAgainst,
            stmsPtsAgainstPerGame: data.teamStatsTotals[0].stats.defense.ptsAgainstPerGame,
            // miscellaneous: seasonalTeamStats
            stmsFouls: data.teamStatsTotals[0].stats.miscellaneous.fouls,
            stmsFoulsPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulsPerGame,
            stmsFoulsDrawn: data.teamStatsTotals[0].stats.miscellaneous.foulsDrawn,
            stmsFoulsDrawnPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulsDrawnPerGame,
            stmsFoulPers: data.teamStatsTotals[0].stats.miscellaneous.foulPers,
            stmsFoulPersPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulPersPerGame,
            stmsFoulPersDrawn: data.teamStatsTotals[0].stats.miscellaneous.foulPersDrawn,
            stmsFoulPersDrawnPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulPersDrawnPerGame,
            stmsFoulTech: data.teamStatsTotals[0].stats.miscellaneous.foulTech,
            stmsFoulTechPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulTechPerGame,
            stmsFoulTechDrawn: data.teamStatsTotals[0].stats.miscellaneous.foulTechDrawn,
            stmsFoulTechDrawnPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulTechDrawnPerGame,
            stmsFoulFlag1: data.teamStatsTotals[0].stats.miscellaneous.foulFlag1,
            stmsFoulFlag1PerGame: data.teamStatsTotals[0].stats.miscellaneous.foulFlag1PerGame,
            stmsFoulFlag1Drawn: data.teamStatsTotals[0].stats.miscellaneous.foulFlag1Drawn,
            stmsFoulFlag1DrawnPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulFlag1DrawnPerGame,
            stmsFoulFlag2: data.teamStatsTotals[0].stats.miscellaneous.foulFlag2,
            stmsFoulFlag2PerGame: data.teamStatsTotals[0].stats.miscellaneous.foulFlag2PerGame,
            stmsFoulFlag2Drawn: data.teamStatsTotals[0].stats.miscellaneous.foulFlag2Drawn,
            stmsFoulFlag2DrawnPerGame: data.teamStatsTotals[0].stats.miscellaneous.foulFlag2DrawnPerGame,
            stmsEjections: data.teamStatsTotals[0].stats.miscellaneous.ejections,
            stmsPlusMinus: data.teamStatsTotals[0].stats.miscellaneous.plusMinus,
            stmsPlusMinusPerGame : data.teamStatsTotals[0].stats.miscellaneous.plusMinusPerGame,
            // standings: seasonalTeamStats
            stmsWins: data.teamStatsTotals[0].stats.standings.wins,
            stmsLosses: data.teamStatsTotals[0].stats.standings.losses,
            stmsWinPct: data.teamStatsTotals[0].stats.standings.winPct,
            stmsGamesBack: data.teamStatsTotals[0].stats.standings.gamesBack
        }
        return seasonalTeamStats;
    }
}


const headerCheck = {
    plyrLastUpdatedOn: "Last Updated On",
    plyrFirstName: "First Name",
    plyrLastName: "Last Name",
    plyrCurrentTeamAbbreviation: "Team Abbreviation",
    plyrPrimaryPosition: "Position",
    plyrAlternatePositions: "Alternate Position",
    plyrJerseyNumber: "Jersey Number",
    plyrHeight: "Height",
    plyrWeight: "Weight",
    plyrBirthDate: "Birth Date",
    plyrAge: "Age",
    plyrBirthCity: "Birth City",
    plyrBirthCountry: "Birth Country",
    plyrRookie: "Rookie Status",
    plyrHighSchool: "High School",
    plyrCollege: "College",
    plyrHandednessShoots: "Dominant Hand",
    plyrSocialMediaType: "Social Media Type",
    plyrSocialMediaValue: "Social Media Account",
    plyrContractStartYear: "Contract Start Year",
    plyrContractBaseSalary: "Base Salary",
    plyrContractMinorsSalary: "Minors Salary",
    plyrContractSigningBonus: "Signing Bonus",
    plyrContractOtherBonuses: "Other Bonuses",
    plyrContractCapHit: "Cap Hit",
    plyrContractNoTradeClause: "No Trade Clause",
    plyrContractModifiedTradeClause: "Modified Trade Clause",
    plyrContractnoMovementClause: "Movement Clause",
    plyrContractSigningTeamId: "Signing Team ID",
    plyrContractSigningTeamAbbreviation: "Signing Team Abbreviation",
    plyrContractSignedOn: "Signed On",
    plyrContractTotalYears: "Total Years",
    plyrContractTotalSalary: "Total Salary",
    plyrContractTotalBonuses: "Total Bonuses",
    plyrContractExpiryStatus: "Expiry Status",
    plyrContractAnnualSalary: "Annual Salary",
    plyrDraftedYear: "Draft Year",
    plyrDraftedTeamAbbreviation: "Draft Team Abbreviation",
    plyrDraftedPickTeamAbbreviation: "Pick Team Abbreviation",
    plyrDraftedRound: "Draft Round",
    plyrOverallPick: "Overall Pick Number",
    plyrCurrentRosterStatus: "Roster Status",
    plyrCurrentInjury: "Current Injury",
    plyrId: "Player ID",
    plyrCurrentTeamId: "Team ID",
    plyrOfficialImageSrc: "Image",
    plyrDraftedTeamId: "Draft Team ID",
    plyrDraftedPickTeamId: "Pick Team ID",
    plyrDraftedRoundPick: "Draft Round Pick Number",
    plyrExternalMappingsSource: "External Mapping Source",
    plyrExternalMappingsId: "ExternalMappingsId",
    plyrTeamAsOfDateId: "As of Date Team ID",
    plyrTeamAsOfDateAbbreviation: "As of Date Team Abbreviation",

    plijCurrentRosterStatus: "Roster Status",
    plijCurrentInjuries: "Current Injury",
    plijCurrentInjuryDescription: "Injury Description",
    plijCurrentInjuryPlayingProbability: "Playing Probability",
    plijSocialMediaAccountsMediaType: "Social Media Type",
    plijSocialMediaAccountsValue: "Social Media Link",
    plijLastUpdatedOn: "Last Updated On",
    plijFirstName: "First Name",
    plijLastName: "Last Name",
    plijPrimaryPosition: "Position",
    plijJerseyNumber: "Jersey Number",
    plijCurrentTeamId: "Team ID",
    plijCurrentTeamAbbreviation: "Team Abbreviation",
    plijHeight: "Height",
    plijWeight: "Weight",
    plijBirthDate: "Birth Date",
    plijAge: "Age",
    plijBirthCity: "Birth City",
    plijHighSchool: "High School",
    plijCollege: "College",
    plijHandednessShoots: "Dominant Hand",
    plijOfficialImageSrc: "Image",
    plijId: "Player ID",

    dpglGameId: "Game ID",
    dpglGameStartTime: "Game Start Time",
    dpglGamesAwayTeamAbbreviation: "Away Team",
    dpglGamesHomeTeamAbbreviation: "Home Team",
    dpglEjections: "Ejections",
    dpglPlusMinus: "Plus-Minus",
    dpglPlusMInusPerGame: "Plus-Minus per Game",
    dpglMinSeconds: "Minutes",
    dpglMinSecondsPerGame: "Minutes per Game",
    dpglGamesStarted: "Games Started",
    dpglFg2PtAtt: "2pt Attempts",
    dpglFg2PtAttPerGame: "2pt Attempts per Game",
    dpglFg2PtMade: "2pt Made",
    dpglFg2PtMadePerGame: "2pt Made per Game",
    dpglFg2PtPct: "2pt Percentage",
    dpglFg3PtAtt: "3pt Attempts",
    dpglFg3PtAttPerGame: "3pt Attempts per Game",
    dpglFg3PtMade: "3pt Made",
    dpglFg3PtMadePerGame: "3pt Made per Game",
    dpglFg3PtPct: "3pt Percentage",
    dpglFgAtt: "Field Goal Attempts",
    dpglFgAttPerGame: "Field Goal Attempts per Game",
    dpglFgMade: "Field Goals Made",
    dpglFgMadePerGame: "Field Goals Made per Game",
    dpglFgPct: "Field Goal Percentage",
    dpglFtAtt: "Free Throw Attempts",
    dpglFtAttPerGame: "Free Throw Attempts per Game",
    dpglFtMade: "Free Throws Made",
    dpglFtMadePerGame: "Free Throws Made per Game",
    dpglFtPct: "Free Throw Percentage",
    dpglOffReb: "Offensive Rebounds",
    dpglOffRebPerGame: "Offensive Rebounds per Game",
    dpglDefReb: "Defensive Rebounds",
    dpglDefRebPerGame: "Defensive Rebounds per Game",
    dpglReb: "Rebounds",
    dpglRebPerGame: "Rebounds per Game",
    dpglAst: "Assists",
    dpglAstPerGame: "Assists per Game",
    dpglPts: "Points",
    dpglPtsPerGame: "Points per Game",
    dpglTov: "Turnovers",
    dpglTovPerGame: "Turnovers per Game",
    dpglStl: "Steals",
    dpglStlPerGame: "Steals per Game",
    dpglBlk: "Blocks",
    dpglBlkPerGame: "Blocks per Game",
    dpglBlkAgainst: "Blocks Against",
    dpglBlkAgainstPerGame: "Blocks Against per Game",
    dpglFouls: "Fouls",
    dpglFoulsPerGame: "Fouls per Game",
    dpglFoulsDrawn: "Fouls Drawn",
    dpglFoulsDrawnPerGame: "Fouls Drawn per Game",
    dpglFoulPers: "Personal Fouls",
    dpglFoulPersPerGame: "Personal Fouls per Game",
    dpglFoulPersDrawn: "Personal Fouls Drawn",
    dpglFoulPersDrawnPerGame: "Personal Fouls Drawn per Game",
    dpglFoulTech: "Technical Fouls",
    dpglFoulTechPerGame: "Technical Fouls per Game",
    dpglFoulTechDrawn: "Technical Fouls Drawn",
    dpglFoulTechDrawnPerGame: "Technical Fouls Drawn per Game",
    dpglFoulFlag1: "Flagrant 1 Fouls",
    dpglFoulFlag1PerGame: "Flagrant 1 Fouls per Game",
    dpglFoulFlag1Drawn: "Flagrant 1 Fouls Drawn",
    dpglFoulFlag1DrawnPerGame: "Flagrant 1 Fouls Drawn per Game",
    dpglFoulFlag2: "Flagrant 2 Fouls",
    dpglFoulFlag2PerGame: "Flagrant 2 Fouls per Game",
    dpglFoulFlage2Drawn: "Flagrant 2 Fouls Drawn",
    dpglFoulFlag2DrawnPerGame: "Flagrant 2 Fouls Drawn per Game",
    dpglLatestUpdatedOn: "Last Updated On",
    dpglPlayerId: "Player ID",
    dpglPlayerFirstName: "First Name",
    dpglPlayerLastName: "Last Name",
    dpglPlayerPosition: "Position",
    dpglPlayerJerseyNumber: "Jersey Number",
    dpglTeamId: "Team ID",
    dpglTeamAbbreviation: "Team Abbreviation",

    dtglLastUpdatedOn: "Last Updated On",
    dtglGameId: "Game ID",
    dtglGameStartTime: "Game Start Time",
    dtglGameAwayTeamAbbreviation: "Away Team",
    dtglGameHomeTeamAbbreviation: "Home Team",
    dtglTeamId: "Team ID",
    dtglTeamAbbreviation: "Team Abbreviation",
    dtglEjections: "Ejections",
    dtglPlusMinus: "Plus-Minus",
    dtglPlusMinusPerGame: "Plus-Minus per Game",
    dtglWins: "Wins",
    dtglLosses: "Losses",
    dtglWinPct: "Win Percentage",
    dtglGamesBack: "Games Back",
    dtglFg2PtAtt: "2pt Attempts",
    dtglFg2PtAttPerGame: "2pt Attempts per Game",
    dtglFg2PtMade: "2pt Made",
    dtglFg2PtMadePerGame: "2pt Made per Game",
    dtglFg2PtPct: "2pt Percentage",
    dtglFg3PtAtt: "3pt Attempts",
    dtglFg3PtAttPerGame: "3pt Attempts per Game",
    dtglFg3PtMade: "3pt Made",
    dtglFg3PtMadePerGame: "3pt Made per Game",
    dtglFg3PtPct: "3pt Percentage",
    dtglFgAtt: "Field Goal Attempts",
    dtglFgAttPerGame: "Field Goal Attempts per Game",
    dtglFgMade: "Field Goals Made",
    dtglFgMadePerGame: "Field Goals Made per Game",
    dtglFgPct: "Field Goal Percentage",
    dtglFtAtt: "Free Throw Attempts",
    dtglFtAttPerGame: "Free Throw Attempts per Game",
    dtglFtMade: "Free Throws Made",
    dtglFtMadePerGame: "Free Throws Made per Game",
    dtglFtPct: "Free Throw Percentage",
    dtglOffReb: "Offensive Rebounds",
    dtglOffRebPerGame: "Offensive Rebounds per Game",
    dtglDefReb: "Defensive Rebounds",
    dtglDefRebPerGame: "Defensive Rebounds per Game",
    dtglReb: "Rebounds",
    dtglRebPerGame: "Rebounds per Game",
    dtglAst: "Assists",
    dtglAstPerGame: "Assists per Game",
    dtglPts: "Points",
    dtglPtsPerGame: "Points per Game",
    dtglPtsAgainst: "Points Against",
    dtglPtsAgainstPerGame: "Points Against per Game",
    dtglTov: "Turnovers",
    dtglTovPerGame: "Turnovers per Game",
    dtglStl: "Steals",
    dtglStlPerGame: "Steals per Game",
    dtglBlk: "Blocks",
    dtglBlkPerGame: "Blocks per Game",
    dtglBlkAgainst: "Blocks Against",
    dtglBlkAgainstPerGame: "Blocks Against per Game",
    dtglFouls: "Fouls",
    dtglFoulsPerGame: "Fouls per Game",
    dtglFoulsDrawn: "Fouls Drawn",
    dtglFoulsDrawnPerGame: "Fouls Drawn per Game",
    dtglFoulPers: "Personal Fouls",
    dtglFoulPersPerGame: "Personal Fouls per Game",
    dtglFoulPersDrawn: "Personal Fouls Drawn",
    dtglFoulPersDrawnPerGame: "Personal Fouls Drawn per Game",
    dtglFoulTech: "Technical Fouls",
    dtglFoulTechPerGame: "Technical Fouls per Game",
    dtglFoulTechDrawn: "Technical Fouls Drawn",
    dtglFoulTechDrawnPerGame: "Technical Fouls Drawn per Game",
    dtglFoulFlag1: "Flagrant 1 Fouls",
    dtglFoulFlag1PerGame: "Flagrant 1 Fouls per Game",
    dtglFoulFlag1Drawn: "Flagrant 1 Fouls Drawn",
    dtglFoulFlag1DrawnPerGame: "Flagrant 1 Fouls Drawn per Game",
    dtglFoulFlag2: "Flagrant 2 Fouls",
    dtglFoulFlag2PerGame: "Flagrant 2 Fouls per Game",
    dtglFoulFlag2Drawn: "Flagrant 2 Fouls Drawn",

    splsLastUpdatedOn: "Last updated On",
    splsPlayerId: "Player ID",
    splsPlayerFirstName: "First Name",
    splsPlayerLastName: "Last Name",
    splsJerseyNumber: "Jersey Number",
    splsCurrentTeamId: "Team ID",
    splsCurrentTeamAbbreviation: "Team Abbreviation",
    splsPlayerCurrentRosterStatus: "Roster Status",
    splsPlayerCurrentInjury: "Current Injury",
    splsPlayerHeight: "Height",
    splsPlayerWeight: "Weight",
    splsPlayerBirthDate: "Birth Date",
    splsPlayerAge: "Age",
    splsPlayerBirthCity: "Birth City",
    splsPlayerBirthCountry: "Birth Country",
    splsPlayerRookie: "Rookie Status",
    splsPlayerHandednessShoots: "Dominant Hand",
    splsPlayerOfficialImageSrc: "Image",
    splsPlayerSocialMediaAccounts: "Social Media",
    splsPlayerTeamId: "Team ID",
    splsPlayerTeamAbbreviation: "Team Abbreviation",
    splsPlayerGamesPlayed: "Games Played", 
    splsEjections: "Ejections",
    splsPlusMinus: "Plus-Minus",
    splsPlusMinusPerGame: "Plus-Minus per Game",
    splsMinSeconds: "Minutes",
    splsMinSecondsPerGame: "Minutes per Game",
    splsGamesStarted: "Games Started",
    splsFg2PtAtt: "2pt Attempts",
    splsFg2PtAttPerGame: "2pt Attempts per Game",
    splsFg2PtMade: "2pt Made",
    splsFg2PtMadePerGame: "2pt Made per Game",
    splsFg2PtPct: "2pt Percentage",
    splsFg3PtAtt: "3pt Attempts",
    splsFg3PtAttPerGame: "3pt Attempts per Game",
    splsFg3PtMade: "3pt Made",
    splsFg3PtMadePerGame: "3pt Made per Game",
    splsFg3PtPct: "3pt Percentage",
    splsFtAtt: "Field Goal Attempts",
    splsFtAttPerGame: "Field Goal Attempts per Game",
    splsFtMade: "Field Goals Made",
    splsFtMadePerGame: "Field Goals Made per Game",
    splsFtPct: "Field Goal Percentage",
    splsFtAtt: "Free Throw Attempts",
    splsFtAttPerGame: "Free Throw Attempts per Game",
    splsFtMade: "Free Throws Made",
    splsFtMadePerGame: "Free Throws Made per Game",
    splsFtPct: "Free Throw Percentage",
    splsOffReb: "Offensive Rebounds",
    splsOffRebPerGame: "Offensive Rebounds per Game",
    splsDefReb: "Defensive Rebounds",
    splsDefRebPerGame: "Defensive Rebounds per Game",
    splsReb: "Rebounds",
    splsRebPerGame: "Rebounds per Game",
    splsAst: "Assists",
    splsAstPerGame: "Assists per Game",
    splsPts: "Points",
    splsPtsPerGame: "Points per Game",
    splsTov: "Turnovers",
    splsTovPerGame: "Turnovers per Game",
    splsStl: "Steals",
    splsStlPerGame: "Steals per Game",
    splsBlk: "Blocks",
    splsBlkPerGame: "Blocks per Game",
    splsBlkAgainst: "Blocks Against",
    splsBlkAgainstPerGame: "Blocks Against per Game",
    splsFouls: "Fouls",
    splsFoulsPerGame: "Fouls per Game",
    splsFoulsDrawn: "Fouls Drawn",
    splsFoulsDrawnPerGame: "Fouls Drawn per Game",
    splsFoulsPerGame: "Personal Fouls",
    splsFoulsfoulPersPerGame: "Personal Fouls per Game",
    splsFoulPersDrawn: "Personal Fouls Drawn",
    splsFoulPersDrawnPerGame: "Personal Fouls Drawn per Game",
    splsFoulTech: "Technical Fouls",
    splsFoulTechPerGame: "Technical Fouls per Game",
    splsFoulTechDrawn: "Technical Fouls Drawn",
    splsFoulTechDrawnPerGame: "Technical Fouls Drawn per Game",
    splsFoulFlag1: "Flagrant 1 Fouls",
    splsFoulFlag1PerGame: "Flagrant 1 Fouls per Game",
    splsFoulFlag1Drawn: "Flagrant 1 Fouls Drawn",
    splsFoulFlag1DrawnPerGame: "Flagrant 1 Fouls Drawn per Game",
    splsFoulFlag2: "Flagrant 2 Fouls",
    splsFoulFlag2PerGame: "Flagrant 2 Fouls per Game",
    splsFoulFlag2Drawn: "Flagrant 2 Fouls Drawn",
    splsFoulFlag2DrawnPerGame: "Flagrant 2 Fouls Drawn per Game",

    stmsLastUpdatedOn: "Last Updated On",
    stmsTeamId: "Team ID",
    stmsTeamCity: "Team City",
    stmsTeamName: "Team Name",
    stmsTeamAbbreviation: "Team Abbreviation",
    stmsTeamHomeVenueId: "Home Venue ID",
    stmsTeamHomeVenueName: "Home Venue Name",
    stmsTeamColoursHex: "Team Colors",
    stmsSocialMediaAccounts: "Social Media",
    stmsOfficialLogoImageSrc: "Logo Image",
    stmsGamesPlayed: "Games Played",
    stmsEjections: "Ejections",
    stmsPlusMinus: "Plus-Minus",
    stmsPlusMinusPerGame : "Plus-Minus per Game",            
    stmsWins: "Wins",
    stmsLosses: "Losses",
    stmsWinPct: "Win Percentage",
    stmsGamesBack: "Games Back",
    stmsFg2PtAtt: "2pt Attempts",
    stmsFg2PtAttPerGame: "2pt Attempts per Game",
    stmsFg2PtMade: "2pt Made",
    stmsFg2PtMadePerGame: "2pt Made per Game",
    stmsFg2PtPct: "2pt Percentage",
    stmsFg3PtAtt: "3pt Attempts",
    stmsFg3PtAttPerGame: "3pt Attempts per Game",
    stmsFg3PtMade: "3pt Made",
    stmsFg3PtMadePerGame: "3pt Made per Game",
    stmsFg3PtPct: "3pt Percentage",
    stmsFgAtt: "Field Goal Attempts",
    stmsFgAttPerGame: "Field Goal Attempts per Game",
    stmsFgMade: "Field Goals Made",
    stmsFgMadePerGame: "Field Goals Made per Game",
    stmsFgPct: "Field Goal Percentage",
    stmsFtAtt: "Free Throw Attempts",
    stmsFtAttPerGame: "Free Throw Attempts per Game",
    stmsFtMade: "Free Throws Made",
    stmsFtMadePerGame: "Free Throws Made per Game",
    stmsFtPct: "Free Throw Percentage",
    stmsOffReb: "Offensive Rebounds",
    stmsOffRebPerGame: "Offensive Rebounds per Game",
    stmsDefReb: "Defensive Rebounds",
    stmsDefRebPerGame: "Defensive Rebounds per Game",
    stmsReb: "Rebounds",
    stmsRebPerGame: "Rebounds per Game",
    stmsAst: "Assists",
    stmsAstPerGame: "Assists per Game",
    stmsPts: "Points",
    stmsPtsPerGame: "Points per Game",
    stmsPtsAgainst: "Points Against",
    stmsPtsAgainstPerGame: "Points Against per Game",
    stmsTov: "Turnovers",
    stmsTovPerGame: "Turnovers per Game",
    stmsStl: "Steals",
    stmsStlPerGame: "Steals per Game",
    stmsBlk: "Blocks",
    stmsBlkPerGame: "Blocks per Game",
    stmsBlkAgainst: "Blocks Against",
    stmsBlkAgainstPerGame: "Blocks Against per Game",
    stmsFouls: "Fouls",
    stmsFoulsPerGame: "Fouls per Game",
    stmsFoulsDrawn: "Fouls Drawn",
    stmsFoulsDrawnPerGame: "Fouls Drawn per Game",
    stmsFoulPers: "Personal Fouls",
    stmsFoulPersPerGame: "Personal Fouls per Game",            
    stmsFoulPersDrawn: "Personal Fouls Drawn",
    stmsFoulPersDrawnPerGame: "Personal Fouls Drawn per Game",
    stmsFoulTech: "Technical Fouls",
    stmsFoulTechPerGame: "Technical Fouls per Game",            
    stmsFoulTechDrawn: "Technical Fouls Drawn",
    stmsFoulTechDrawnPerGame: "Technical Fouls Drawn per Game",
    stmsFoulFlag1: "Flagrant 1 Fouls",
    stmsFoulFlag1PerGame: "Flagrant 1 Fouls per Game",
    stmsFoulFlag1Drawn: "Flagrant 1 Fouls Drawn",
    stmsFoulFlag1DrawnPerGame: "Flagrant 1 Fouls Drawn per Game",
    stmsFoulFlag2: "Flagrant 2 Fouls",
    stmsFoulFlag2PerGame: "Flagrant 2 Fouls per Game",            
    stmsFoulFlag2Drawn: "Flagrant 2 Fouls Drawn",
    stmsFoulFlag2DrawnPerGame: "Flagrant 2 Fouls Drawn per Game"
} 


module.exports = {API, headerCheck};