DROP DATABASE IF EXISTS bball_db;

CREATE DATABASE bball_db;

USE bball_db;

CREATE TABLE users (
    id INTEGER NOT NULL AUTO_INCREMENT,
    user VARCHAR (255) NOT NULL,
    completed BOOLEAN DEFAULT 0,
    PRIMARY KEY (id)
);

